# GENERATED by scripts/gen.py from the public OpenAPI spec. Do not edit; run `python scripts/gen.py`.

"""Error-code subclasses: codes from `x-relay-error-codes`, HTTP status from scripts/error_statuses.json."""

from __future__ import annotations

from .._exceptions import (
    AuthenticationError,
    CapacityError,
    ConflictError,
    GoneError,
    InsufficientCreditsError,
    InvalidRequestError,
    NotFoundError,
    PermissionDeniedError,
    ProviderError,
    RateLimitError,
    RelayInternalError,
    UpstreamTimeoutError,
    ValidationError,
    RelayAPIError,
)


class AccountInactiveError(PermissionDeniedError):
    """`ACCOUNT_INACTIVE` (HTTP 403)."""


class AmountMismatchError(ConflictError):
    """`AMOUNT_MISMATCH` (HTTP 409)."""


class AutoTopupNotConfiguredError(ConflictError):
    """`AUTO_TOPUP_NOT_CONFIGURED` (HTTP 409)."""


class BankTransferNotAvailableError(PermissionDeniedError):
    """`BANK_TRANSFER_NOT_AVAILABLE` (HTTP 403)."""


class BillingProfileRequiredError(ConflictError):
    """`BILLING_PROFILE_REQUIRED` (HTTP 409)."""


class CapacityExhaustedError(CapacityError):
    """`CAPACITY_EXHAUSTED` (HTTP 503)."""


class ContentPolicyDeclinedError(ValidationError):
    """`CONTENT_POLICY_DECLINED` (HTTP 422)."""


class CredentialNotPermittedError(PermissionDeniedError):
    """`CREDENTIAL_NOT_PERMITTED` (HTTP 403)."""


class CustomerNotFoundError(NotFoundError):
    """`CUSTOMER_NOT_FOUND` (HTTP 404)."""


class DocumentNotAvailableError(ConflictError):
    """`DOCUMENT_NOT_AVAILABLE` (HTTP 409)."""


class FileNotFoundError(NotFoundError):
    """`FILE_NOT_FOUND` (HTTP 404)."""


class FileQuotaExceededError(RateLimitError):
    """`FILE_QUOTA_EXCEEDED` (HTTP 429)."""


class FileTooLargeError(RelayAPIError):
    """`FILE_TOO_LARGE` (HTTP 413)."""


class FileTypeUnsupportedError(RelayAPIError):
    """`FILE_TYPE_UNSUPPORTED` (HTTP 415)."""


class IdempotencyInProgressError(ConflictError):
    """`IDEMPOTENCY_IN_PROGRESS` (HTTP 409)."""


class IdempotencyKeyReusedError(ValidationError):
    """`IDEMPOTENCY_KEY_REUSED` (HTTP 422)."""


class ImageNoOutputError(ProviderError):
    """`IMAGE_NO_OUTPUT` (HTTP 502)."""


class ImageTextResponseError(ValidationError):
    """`IMAGE_TEXT_RESPONSE` (HTTP 422)."""


class InstancesUnavailableError(CapacityError):
    """`INSTANCES_UNAVAILABLE` (HTTP 503)."""


class InstanceLimitError(RateLimitError):
    """`INSTANCE_LIMIT` (HTTP 429)."""


class InstanceNotFoundError(NotFoundError):
    """`INSTANCE_NOT_FOUND` (HTTP 404)."""


class InstanceNotReadyError(ConflictError):
    """`INSTANCE_NOT_READY` (HTTP 409)."""


class InternalError(RelayInternalError):
    """`INTERNAL_ERROR` (HTTP 500)."""


class InvalidApiKeyError(AuthenticationError):
    """`INVALID_API_KEY` (HTTP 401)."""


class InvalidTokenError(AuthenticationError):
    """`INVALID_TOKEN` (HTTP 401)."""


class InvoiceNotFoundError(NotFoundError):
    """`INVOICE_NOT_FOUND` (HTTP 404)."""


class InvoiceNotOpenError(ConflictError):
    """`INVOICE_NOT_OPEN` (HTTP 409)."""


class KeyBudgetExhaustedError(InsufficientCreditsError):
    """`KEY_BUDGET_EXHAUSTED` (HTTP 402)."""


class KeyLimitReachedError(PermissionDeniedError):
    """`KEY_LIMIT_REACHED` (HTTP 403)."""


class KeyNotFoundError(NotFoundError):
    """`KEY_NOT_FOUND` (HTTP 404)."""


class KeyNotOwnedError(PermissionDeniedError):
    """`KEY_NOT_OWNED` (HTTP 403)."""


class KeyRevokedError(AuthenticationError):
    """`KEY_REVOKED` (HTTP 401)."""


class MandateNotFoundError(NotFoundError):
    """`MANDATE_NOT_FOUND` (HTTP 404)."""


class MissingCredentialsError(AuthenticationError):
    """`MISSING_CREDENTIALS` (HTTP 401)."""


class ModelNotAvailableError(PermissionDeniedError):
    """`MODEL_NOT_AVAILABLE` (HTTP 403)."""


class ModelNotFoundError(NotFoundError):
    """`MODEL_NOT_FOUND` (HTTP 404)."""


class ModelRetiredError(PermissionDeniedError):
    """`MODEL_RETIRED` (HTTP 403)."""


class PaymentServiceUnavailableError(CapacityError):
    """`PAYMENT_SERVICE_UNAVAILABLE` (HTTP 503)."""


class PromoAlreadyRedeemedError(ConflictError):
    """`PROMO_ALREADY_REDEEMED` (HTTP 409)."""


class PromoCodeExhaustedError(GoneError):
    """`PROMO_CODE_EXHAUSTED` (HTTP 410)."""


class PromoCodeExpiredError(GoneError):
    """`PROMO_CODE_EXPIRED` (HTTP 410)."""


class PromoCodeInvalidError(NotFoundError):
    """`PROMO_CODE_INVALID` (HTTP 404)."""


class ProviderSchemaMismatchError(ProviderError):
    """`PROVIDER_SCHEMA_MISMATCH` (HTTP 502)."""


class ProviderUnavailableError(ProviderError):
    """`PROVIDER_UNAVAILABLE` (HTTP 502)."""


class RateLimitedError(RateLimitError):
    """`RATE_LIMITED` (HTTP 429)."""


class ReceivableLimitExceededError(ConflictError):
    """`RECEIVABLE_LIMIT_EXCEEDED` (HTTP 409)."""


class ReceivableOverdueError(ConflictError):
    """`RECEIVABLE_OVERDUE` (HTTP 409)."""


class RefundNotFoundError(NotFoundError):
    """`REFUND_NOT_FOUND` (HTTP 404)."""


class ScopeDeniedError(PermissionDeniedError):
    """`SCOPE_DENIED` (HTTP 403)."""


class SuperkeyConflictError(ConflictError):
    """`SUPERKEY_CONFLICT` (HTTP 409)."""


class SystemKeyImmutableError(InvalidRequestError):
    """`SYSTEM_KEY_IMMUTABLE` (HTTP 400)."""


class TaskNotFoundError(NotFoundError):
    """`TASK_NOT_FOUND` (HTTP 404)."""


class TierFeatureUnavailableError(PermissionDeniedError):
    """`TIER_FEATURE_UNAVAILABLE` (HTTP 403)."""


class TopupNotFoundError(NotFoundError):
    """`TOPUP_NOT_FOUND` (HTTP 404)."""


class UpstreamError(ProviderError):
    """`UPSTREAM_ERROR` (HTTP 502)."""


class UpstreamInvalidRequestError(InvalidRequestError):
    """`UPSTREAM_INVALID_REQUEST` (HTTP 400)."""


class WebhookDeliveryNotFoundError(NotFoundError):
    """`WEBHOOK_DELIVERY_NOT_FOUND` (HTTP 404)."""


class WorkflowNotFoundError(NotFoundError):
    """`WORKFLOW_NOT_FOUND` (HTTP 404)."""


class WorkflowRunLimitReachedError(RateLimitError):
    """`WORKFLOW_RUN_LIMIT_REACHED` (HTTP 429)."""


class WorkflowRunNotCancellableError(ConflictError):
    """`WORKFLOW_RUN_NOT_CANCELLABLE` (HTTP 409)."""


class WorkflowRunNotFoundError(NotFoundError):
    """`WORKFLOW_RUN_NOT_FOUND` (HTTP 404)."""


# Every catalog code (`x-relay-error-codes`) → its class.
ERROR_CODE_CLASSES: dict[str, type[RelayAPIError]] = {
    "ACCOUNT_INACTIVE": AccountInactiveError,
    "AMOUNT_MISMATCH": AmountMismatchError,
    "AUTO_TOPUP_NOT_CONFIGURED": AutoTopupNotConfiguredError,
    "BANK_TRANSFER_NOT_AVAILABLE": BankTransferNotAvailableError,
    "BILLING_PROFILE_REQUIRED": BillingProfileRequiredError,
    "CAPACITY_EXHAUSTED": CapacityExhaustedError,
    "CONTENT_POLICY_DECLINED": ContentPolicyDeclinedError,
    "CREDENTIAL_NOT_PERMITTED": CredentialNotPermittedError,
    "CUSTOMER_NOT_FOUND": CustomerNotFoundError,
    "DOCUMENT_NOT_AVAILABLE": DocumentNotAvailableError,
    "FILE_NOT_FOUND": FileNotFoundError,
    "FILE_QUOTA_EXCEEDED": FileQuotaExceededError,
    "FILE_TOO_LARGE": FileTooLargeError,
    "FILE_TYPE_UNSUPPORTED": FileTypeUnsupportedError,
    "IDEMPOTENCY_IN_PROGRESS": IdempotencyInProgressError,
    "IDEMPOTENCY_KEY_REUSED": IdempotencyKeyReusedError,
    "IMAGE_NO_OUTPUT": ImageNoOutputError,
    "IMAGE_TEXT_RESPONSE": ImageTextResponseError,
    "INSTANCES_UNAVAILABLE": InstancesUnavailableError,
    "INSTANCE_LIMIT": InstanceLimitError,
    "INSTANCE_NOT_FOUND": InstanceNotFoundError,
    "INSTANCE_NOT_READY": InstanceNotReadyError,
    "INSUFFICIENT_CREDITS": InsufficientCreditsError,
    "INTERNAL_ERROR": InternalError,
    "INVALID_API_KEY": InvalidApiKeyError,
    "INVALID_TOKEN": InvalidTokenError,
    "INVOICE_NOT_FOUND": InvoiceNotFoundError,
    "INVOICE_NOT_OPEN": InvoiceNotOpenError,
    "KEY_BUDGET_EXHAUSTED": KeyBudgetExhaustedError,
    "KEY_LIMIT_REACHED": KeyLimitReachedError,
    "KEY_NOT_FOUND": KeyNotFoundError,
    "KEY_NOT_OWNED": KeyNotOwnedError,
    "KEY_REVOKED": KeyRevokedError,
    "MANDATE_NOT_FOUND": MandateNotFoundError,
    "MISSING_CREDENTIALS": MissingCredentialsError,
    "MODEL_NOT_AVAILABLE": ModelNotAvailableError,
    "MODEL_NOT_FOUND": ModelNotFoundError,
    "MODEL_RETIRED": ModelRetiredError,
    "PAYMENT_SERVICE_UNAVAILABLE": PaymentServiceUnavailableError,
    "PROMO_ALREADY_REDEEMED": PromoAlreadyRedeemedError,
    "PROMO_CODE_EXHAUSTED": PromoCodeExhaustedError,
    "PROMO_CODE_EXPIRED": PromoCodeExpiredError,
    "PROMO_CODE_INVALID": PromoCodeInvalidError,
    "PROVIDER_SCHEMA_MISMATCH": ProviderSchemaMismatchError,
    "PROVIDER_UNAVAILABLE": ProviderUnavailableError,
    "RATE_LIMITED": RateLimitedError,
    "RECEIVABLE_LIMIT_EXCEEDED": ReceivableLimitExceededError,
    "RECEIVABLE_OVERDUE": ReceivableOverdueError,
    "REFUND_NOT_FOUND": RefundNotFoundError,
    "SCOPE_DENIED": ScopeDeniedError,
    "SUPERKEY_CONFLICT": SuperkeyConflictError,
    "SYSTEM_KEY_IMMUTABLE": SystemKeyImmutableError,
    "TASK_NOT_FOUND": TaskNotFoundError,
    "TIER_FEATURE_UNAVAILABLE": TierFeatureUnavailableError,
    "TOPUP_NOT_FOUND": TopupNotFoundError,
    "UPSTREAM_ERROR": UpstreamError,
    "UPSTREAM_INVALID_REQUEST": UpstreamInvalidRequestError,
    "UPSTREAM_TIMEOUT": UpstreamTimeoutError,
    "VALIDATION_ERROR": ValidationError,
    "WEBHOOK_DELIVERY_NOT_FOUND": WebhookDeliveryNotFoundError,
    "WORKFLOW_NOT_FOUND": WorkflowNotFoundError,
    "WORKFLOW_RUN_LIMIT_REACHED": WorkflowRunLimitReachedError,
    "WORKFLOW_RUN_NOT_CANCELLABLE": WorkflowRunNotCancellableError,
    "WORKFLOW_RUN_NOT_FOUND": WorkflowRunNotFoundError,
}

__all__ = [
    "AccountInactiveError",
    "AmountMismatchError",
    "AutoTopupNotConfiguredError",
    "BankTransferNotAvailableError",
    "BillingProfileRequiredError",
    "CapacityExhaustedError",
    "ContentPolicyDeclinedError",
    "CredentialNotPermittedError",
    "CustomerNotFoundError",
    "DocumentNotAvailableError",
    "ERROR_CODE_CLASSES",
    "FileNotFoundError",
    "FileQuotaExceededError",
    "FileTooLargeError",
    "FileTypeUnsupportedError",
    "IdempotencyInProgressError",
    "IdempotencyKeyReusedError",
    "ImageNoOutputError",
    "ImageTextResponseError",
    "InstanceLimitError",
    "InstanceNotFoundError",
    "InstanceNotReadyError",
    "InstancesUnavailableError",
    "InternalError",
    "InvalidApiKeyError",
    "InvalidTokenError",
    "InvoiceNotFoundError",
    "InvoiceNotOpenError",
    "KeyBudgetExhaustedError",
    "KeyLimitReachedError",
    "KeyNotFoundError",
    "KeyNotOwnedError",
    "KeyRevokedError",
    "MandateNotFoundError",
    "MissingCredentialsError",
    "ModelNotAvailableError",
    "ModelNotFoundError",
    "ModelRetiredError",
    "PaymentServiceUnavailableError",
    "PromoAlreadyRedeemedError",
    "PromoCodeExhaustedError",
    "PromoCodeExpiredError",
    "PromoCodeInvalidError",
    "ProviderSchemaMismatchError",
    "ProviderUnavailableError",
    "RateLimitedError",
    "ReceivableLimitExceededError",
    "ReceivableOverdueError",
    "RefundNotFoundError",
    "ScopeDeniedError",
    "SuperkeyConflictError",
    "SystemKeyImmutableError",
    "TaskNotFoundError",
    "TierFeatureUnavailableError",
    "TopupNotFoundError",
    "UpstreamError",
    "UpstreamInvalidRequestError",
    "WebhookDeliveryNotFoundError",
    "WorkflowNotFoundError",
    "WorkflowRunLimitReachedError",
    "WorkflowRunNotCancellableError",
    "WorkflowRunNotFoundError",
]
