# GENERATED by scripts/gen.py from the public OpenAPI spec. Do not edit; run `python scripts/gen.py`.

"""Request and response shapes from the public spec: TypedDicts (`total=False`, `Required[...]` where the spec
requires a field) and Literal aliases. Annotations are strings at runtime (never evaluated)."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal, TypedDict

if TYPE_CHECKING:
    from typing_extensions import Required, TypeAlias
else:
    Required = TypeAlias = Any

# Request schema for Automatic Speech Recognition (Whisper).
ASRRequest = TypedDict(
    "ASRRequest",
    {
        "audio_url": 'Required[str]',
        "model": 'Required[Literal["openai/whisper-large-v3", "openai/whisper-1", "openai/gpt-4o-mini-transcribe"]]',
        "language": 'str | None',
        "prompt": 'str | None',
        "temperature": 'float | None',
        "task": 'Literal["transcribe", "translate"] | None',
        "return_timestamps": 'bool | Literal["word"] | None',
        "chunk_length_s": 'int | None',
        "batch_size": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class ASRResponse(TypedDict, total=False):
    """Response schema for ASR transcription."""

    text: Required[str]
    language: str | None
    duration: float | None
    task_id: str | None
    task_address: str | None
    mode: str | None


# Anthropic Messages API request.
AnthropicMessagesRequest = TypedDict(
    "AnthropicMessagesRequest",
    {
        "model": 'Required[str]',
        "messages": 'Required[list[dict[str, Any]]]',
        "max_tokens": 'Required[int]',
        "system": 'str | list[dict[str, Any]] | None',
        "temperature": 'float | None',
        "top_p": 'float | None',
        "top_k": 'int | None',
        "stop_sequences": 'list[str] | None',
        "stream": 'bool | None',
        "tools": 'list[dict[str, Any]] | None',
        "tool_choice": 'dict[str, Any] | None',
        "thinking": 'dict[str, Any] | None',
        "metadata": 'dict[str, Any] | None',
        "service_tier": 'Literal["auto", "standard_only", "priority"] | None',
        "output_config": 'dict[str, Any] | None',
        "cache_control": 'dict[str, Any] | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class AnthropicMessagesResponse(TypedDict, total=False):
    """Anthropic Messages API response"""

    id: str | None
    type: str
    role: str
    model: Required[str]
    content: Required[list[dict[str, Any]]]
    stop_reason: str | None
    stop_sequence: str | None
    usage: dict[str, Any] | None
    task_id: str | None
    task_address: str | None
    mode: str | None


class AnthropicStreamEvent(TypedDict, total=False):
    """One Anthropic Messages SSE event (`message_start`, `content_block_delta`, `message_stop`, …). Framed as `event: <type>` + `data: {json}`."""

    type: str


class AsyncTaskAccepted(TypedDict, total=False):
    """Response returned when async mode is enabled (HTTP 202 Accepted)."""

    task_id: Required[str]
    status: Literal["queued"]
    poll_url: Required[str]
    message: Required[str]


class Availability(TypedDict, total=False):
    """Whether the row's provider says it can deliver this row right now"""

    state: Required[str]
    count: int | None
    checked_at: str | None


class BillingMode(TypedDict, total=False):
    """One priced way to hold the row. `hourly` is the only mode offered"""

    mode: Required[str]
    period_seconds: Required[int]
    term_seconds: int | None
    rate_per_period: Required[float]
    default: Required[bool]


class BillingTerms(TypedDict, total=False):
    """BillingTerms"""

    currency: str
    unit: str
    full_hour_ceil: bool
    starts_at: str
    ends_at: str
    min_commit_hours: Required[float]
    grace_hours: Required[float]


# Request schema for the Bria video upscaler.
BriaVideoUpscaleRequest = TypedDict(
    "BriaVideoUpscaleRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "video_url": 'Required[str]',
        "output_format": 'Literal["mp4_h264", "mp4_h265", "webm_vp9", "mov_h265", "mov_proresks", "mkv_h264", "mkv_h265", "mkv_vp9", "gif"] | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class BriaVideoUpscaleResponse(TypedDict, total=False):
    """Response schema for the Bria video upscaler."""

    urls: Required[list[str]]
    model: Required[str]
    resolution: str | None
    duration: float | None
    task_id: str | None
    task_address: str | None
    mode: str | None


class CatalogResponse(TypedDict, total=False):
    """CatalogResponse"""

    rows: Required[list[CatalogRow]]
    billing: Required[BillingTerms]
    count: Required[int]


class CatalogRow(TypedDict, total=False):
    """CatalogRow"""

    prescription: Required[str]
    service_mode: Required[str]
    display_name: str | None
    description: str
    kind: Required[str]
    cpu: CpuSpec | None
    ram_gb: int | None
    gpu: GpuSpec | None
    npu: NpuSpec | None
    disk_gb: int | None
    network: NetworkSpec | None
    regions: Required[list[str]]
    default_region: str | None
    compatible_images: Required[list[str]]
    ssh_key_types: Required[list[str]]
    lifetime: Lifetime | None
    billing_modes: Required[list[BillingMode]]
    is_override: Required[bool]
    last_spawn: Required[LastSpawn]
    availability: Required[Availability]


class ContainerConnection(TypedDict, total=False):
    """`managed_container`: `ssh -p <port> <user>@<hostname>`."""

    hostname: Required[str]
    port: Required[int]
    user: Required[str]


class CpuSpec(TypedDict, total=False):
    """CpuSpec"""

    model: Required[str]
    vcpu: Required[int]


class CreateKeyRequest(TypedDict, total=False):
    """CreateKeyRequest"""

    name: Required[str]
    restrictions: KeyRestrictions | None
    key_budget: float | None


class CreateKeyResponse(TypedDict, total=False):
    """`POST /v2/customer/keys` 201 body (documentation only — the route"""

    key: Required[str]
    key_id: Required[str]
    name: Required[str]
    status: Required[Literal["active"]]
    created_at: Required[str]
    restrictions: Required[CreatedKeyRestrictions]
    key_budget: Required[float | None]
    is_superkey: Required[bool]
    warning: Required[str]


class CreatedKeyRestrictions(TypedDict, total=False):
    """The restrictions as stored on the new key. Each key appears only when"""

    model_restrictions: list[str] | None
    rate_limits: dict[str, int] | None


class CreditHistoryResponse(TypedDict, total=False):
    """CreditHistoryResponse"""

    transactions: Required[list[CreditTransaction]]
    total: Required[int]
    limit: Required[int]
    offset: Required[int]


class CreditTransaction(TypedDict, total=False):
    """CreditTransaction"""

    action: Required[str]
    amount: Required[int]
    via: Required[str]
    reason: Required[str]
    created_at: Required[str]


class CreditsResponse(TypedDict, total=False):
    """CreditsResponse"""

    balance: Required[float]
    total_consumed: Required[float]
    promo_consumed: float
    total_allocated: Required[float]
    consumed_by_mode: Required[dict[str, float]]
    last_topup: Required[dict[str, Any] | None]
    promos: list[PromoBalance] | None


class CustomerPricingItem(TypedDict, total=False):
    """CustomerPricingItem"""

    mode: Required[str]
    model: Required[str]
    billing_type: str | None
    per_1m_input_tokens: float | None
    per_1m_output_tokens: float | None
    per_1m_cached_input_tokens: float | None
    per_1k_characters: float | None
    per_second_audio: float | None
    per_image: float | None
    per_image_resolution: dict[str, Any] | None
    per_second_video: dict[str, Any] | None
    per_1m_media_input_tokens: float | dict[str, float] | None
    per_1m_media_output_tokens: float | dict[str, float] | None
    context_tier_threshold: int | None
    per_1m_input_tokens_long: float | None
    per_1m_output_tokens_long: float | None
    per_1m_cached_input_tokens_long: float | None
    per_1m_cache_write_5m_input_tokens: float | None
    per_1m_cache_write_1h_input_tokens: float | None
    per_1m_cache_write_5m_input_tokens_long: float | None
    per_1m_cache_write_1h_input_tokens_long: float | None
    is_override: bool


class CustomerPricingResponse(TypedDict, total=False):
    """CustomerPricingResponse"""

    tier: Required[str]
    pricing: Required[list[CustomerPricingItem]]
    total_count: Required[int]
    media_storage: MediaStoragePricing | None
    note: str


class CustomerSettingsResponse(TypedDict, total=False):
    """CustomerSettingsResponse"""

    status: str
    warning_threshold: Required[float]
    updated_at: Required[str]


class CustomerSettingsUpdate(TypedDict, total=False):
    """CustomerSettingsUpdate"""

    warning_threshold: Required[float]


class CustomerUsageResponse(TypedDict, total=False):
    """CustomerUsageResponse"""

    total: Required[int]
    limit: int | None
    has_more: bool
    next_cursor: str | None
    keys: Required[list[KeyWithAnalytics]]
    query: UsageQueryInfo | None


class DedicatedConnection(TypedDict, total=False):
    """`dedicated_machine`: `ssh <user>@<public_ip>`."""

    public_ip: Required[str]
    port: int
    user: Required[str]


# Request schema for Doubao Seedance 1.5 Pro video generation.
DoubaoSeedance15ProRequest = TypedDict(
    "DoubaoSeedance15ProRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'str | None',
        "first_frame_url": 'str | None',
        "last_frame_url": 'str | None',
        "resolution": 'Literal["480p", "720p", "1080p"] | None',
        "ratio": 'Literal["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "adaptive"] | None',
        "duration": 'int | None',
        "generate_audio": 'bool | None',
        "draft": 'bool | None',
        "camera_fixed": 'bool | None',
        "watermark": 'bool | None',
        "seed": 'int | None',
        "service_tier": 'Literal["default", "flex"] | None',
        "execution_expires_after": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class DoubaoSeedance15ProResponse(TypedDict, total=False):
    """Response schema for Doubao Seedance 1.5 Pro video generation."""

    urls: Required[list[str]]
    model: str
    resolution: str | None
    duration: int | None
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Doubao Seedance 2.0 video generation.
DoubaoSeedance20Request = TypedDict(
    "DoubaoSeedance20Request",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'str | None',
        "first_frame_url": 'str | None',
        "last_frame_url": 'str | None',
        "reference_image_url": 'str | None',
        "reference_image_urls": 'list[str] | None',
        "reference_video_url": 'str | None',
        "reference_audio_url": 'str | None',
        "resolution": 'Literal["480p", "720p", "1080p"] | None',
        "ratio": 'Literal["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "adaptive"] | None',
        "duration": 'int | None',
        "generate_audio": 'bool | None',
        "camera_fixed": 'bool | None',
        "watermark": 'bool | None',
        "seed": 'int | None',
        "execution_expires_after": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class DoubaoSeedance20Response(TypedDict, total=False):
    """Response schema for Doubao Seedance 2.0 video generation."""

    urls: Required[list[str]]
    model: str
    resolution: str | None
    duration: int | None
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for the base (non-V2V) Doubao Seedance 2.5 route.
DoubaoSeedance25Request = TypedDict(
    "DoubaoSeedance25Request",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'str | None',
        "first_frame_url": 'str | None',
        "last_frame_url": 'str | None',
        "reference_image_url": 'str | None',
        "reference_image_urls": 'list[str] | None',
        "reference_video_url": 'str | None',
        "reference_audio_url": 'str | None',
        "resolution": 'Literal["480p", "720p", "1080p"] | None',
        "ratio": 'Literal["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "adaptive"] | None',
        "duration": 'int | None',
        "generate_audio": 'bool | None',
        "camera_fixed": 'bool | None',
        "watermark": 'bool | None',
        "seed": 'int | None',
        "execution_expires_after": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


# Request schema for Doubao Seedance 2.5 V2V (video-to-video).
DoubaoSeedance25V2VRequest = TypedDict(
    "DoubaoSeedance25V2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'str | None',
        "first_frame_url": 'str | None',
        "last_frame_url": 'str | None',
        "reference_image_url": 'str | None',
        "reference_image_urls": 'list[str] | None',
        "reference_video_url": 'Required[str]',
        "reference_audio_url": 'str | None',
        "resolution": 'Literal["480p", "720p", "1080p"] | None',
        "ratio": 'Literal["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "adaptive"] | None',
        "duration": 'Required[int]',
        "generate_audio": 'bool | None',
        "camera_fixed": 'bool | None',
        "watermark": 'bool | None',
        "seed": 'int | None',
        "execution_expires_after": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


# Request schema for Doubao Seedance 2.0 V2V (video-to-video).
DoubaoSeedanceV2VRequest = TypedDict(
    "DoubaoSeedanceV2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'str | None',
        "first_frame_url": 'str | None',
        "last_frame_url": 'str | None',
        "reference_image_url": 'str | None',
        "reference_image_urls": 'list[str] | None',
        "reference_video_url": 'Required[str]',
        "reference_audio_url": 'str | None',
        "resolution": 'Literal["480p", "720p", "1080p"] | None',
        "ratio": 'Literal["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "adaptive"] | None',
        "duration": 'int | None',
        "generate_audio": 'bool | None',
        "camera_fixed": 'bool | None',
        "watermark": 'bool | None',
        "seed": 'int | None',
        "execution_expires_after": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class EmbeddingRequest(TypedDict, total=False):
    """OpenAI-compatible text embeddings request (embedding source, direct mode only)."""

    model: Required[str]
    input: Required[str | list[str] | list[int] | list[list[int]]]
    encoding_format: Literal["float", "base64"] | None
    dimensions: int | None
    user: str | None
    mode: Literal["auto", "direct"] | None


class EmbeddingResponse(TypedDict, total=False):
    """OpenAI-compatible embeddings response (passthrough; provider may add fields)."""

    object: str
    data: list[dict[str, Any]]
    model: Required[str]
    usage: dict[str, Any]


class FileListResponse(TypedDict, total=False):
    """FileListResponse"""

    files: Required[list[FileResponse]]
    next_cursor: str | None


class FileResponse(TypedDict, total=False):
    """One hosted object — an upload or a result — as its owner sees it."""

    file_id: Required[str]
    url: Required[str]
    source: Required[Literal["upload", "result"]]
    content_type: str | None
    size_bytes: int | None
    retention: Required[Literal["relay1h", "relay1d", "relay7d", "relay30d"]]
    expires_at: Required[str]
    seconds_left: Required[int]
    cost_usd: float | None
    created_at: Required[str]
    status: Required[Literal["ready", "expired", "deleted"]]
    task_id: str | None
    workflow_run_id: str | None
    used_by: list[str]


# Request schema for FLUX.2-klein-4B image generation (`/v2/image/flux-1/generate`).
Flux1Request = TypedDict(
    "Flux1Request",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "inputs": 'Required[str]',
        "model": 'str | None',
        "width": 'int | None',
        "height": 'int | None',
        "seed": 'int | None',
        "num_inference_steps": 'int | None',
        "guidance_scale": 'float | None',
        "mode": 'Literal["auto", "opengpu", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class Flux1Response(TypedDict, total=False):
    """Response schema for FLUX.1-schnell image generation"""

    images: Required[list[str]]
    model: Required[str]
    width: int | None
    height: int | None
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for FLUX image generation.
FluxRequest = TypedDict(
    "FluxRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "model": 'str | None',
        "width": 'int | None',
        "height": 'int | None',
        "seed": 'int | None',
        "safety_tolerance": 'int | None',
        "output_format": 'Literal["png", "jpeg"] | None',
        "input_image": 'str | None',
        "input_image_2": 'str | None',
        "input_image_3": 'str | None',
        "input_image_4": 'str | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class FluxResponse(TypedDict, total=False):
    """Response schema for FLUX image generation"""

    images: Required[list[str]]
    model: Required[str]
    width: Required[int]
    height: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Gemini image generation / editing.
GeminiRequest = TypedDict(
    "GeminiRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "model": 'str | None',
        "image": 'str | None',
        "images": 'list[str] | None',
        "aspect_ratio": 'Literal["1:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16", "16:9", "21:9"] | None',
        "image_size": 'Literal["0.5K", "1K", "2K", "4K"] | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class GeminiResponse(TypedDict, total=False):
    """Response schema for Gemini image generation"""

    images: Required[list[str]]
    model: Required[str]
    aspect_ratio: Required[str]
    image_size: Required[str]
    finish_reason: str | None
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for the GPT Image 2 family: gpt-image-2 and the two
GptImage2Request = TypedDict(
    "GptImage2Request",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "model": 'Literal["openai/gpt-image-2", "openai/gpt-image-2.5-sunburst", "openai/gpt-image-2.5-flare"]',
        "prompt": 'Required[str]',
        "size": 'Literal["1024x768", "1024x1024", "1024x1536", "1536x1024", "1920x1080", "2560x1440", "3840x2160"] | None',
        "quality": 'Literal["low", "medium", "high"] | None',
        "n": 'int | None',
        "output_format": 'Literal["png", "jpeg"] | None',
        "output_compression": 'int | None',
        "image": 'str | list[str] | None',
        "mask": 'str | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class GptImage2Response(TypedDict, total=False):
    """Response schema for GPT Image 2 generation."""

    images: Required[list[str]]
    model: str
    size: str | None
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for GPT Image image-to-image editing.
GptImageI2IRequest = TypedDict(
    "GptImageI2IRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "image": 'Required[str]',
        "mask": 'str | None',
        "n": 'Literal[1, 2, 3, 4] | None',
        "size": 'Literal["1024x1024", "1024x1536", "1536x1024"] | None',
        "quality": 'Literal["low", "medium", "high"] | None',
        "output_format": 'Literal["png", "jpeg", "webp"] | None',
        "output_compression": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class GptImageI2IResponse(TypedDict, total=False):
    """Response schema for GPT Image image-to-image editing"""

    images: Required[list[str]]
    model: str
    size: str | None
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for GPT Image text-to-image generation.
GptImageT2IRequest = TypedDict(
    "GptImageT2IRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "n": 'Literal[1, 2, 3, 4] | None',
        "size": 'Literal["1024x1024", "1024x1536", "1536x1024"] | None',
        "quality": 'Literal["low", "medium", "high"] | None',
        "output_format": 'Literal["png", "jpeg", "webp"] | None',
        "output_compression": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class GptImageT2IResponse(TypedDict, total=False):
    """Response schema for GPT Image text-to-image generation"""

    images: Required[list[str]]
    model: str
    size: str | None
    task_id: str | None
    task_address: str | None
    mode: str | None


class GpuSpec(TypedDict, total=False):
    """GpuSpec"""

    model: Required[str]
    count: Required[int]
    memory_gb: int | None


# Request schema for HappyHorse 1.1 text-to-video generation.
HappyHorse11T2VRequest = TypedDict(
    "HappyHorse11T2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "resolution": 'Literal["720P", "1080P"] | None',
        "ratio": 'Literal["16:9", "9:16", "1:1", "4:3", "3:4", "4:5", "5:4", "9:21", "21:9"] | None',
        "duration": 'int | None',
        "watermark": 'bool | None',
        "seed": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


# Request schema for HappyHorse 1.0 image-to-video generation.
HappyHorseI2VRequest = TypedDict(
    "HappyHorseI2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "first_frame_url": 'Required[str]',
        "prompt": 'str | None',
        "resolution": 'Literal["720P", "1080P"] | None',
        "duration": 'int | None',
        "watermark": 'bool | None',
        "seed": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


# Request schema for HappyHorse 1.0 reference-image-to-video generation.
HappyHorseR2VRequest = TypedDict(
    "HappyHorseR2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "images": 'Required[list[str]]',
        "resolution": 'Literal["720P", "1080P"] | None',
        "ratio": 'Literal["16:9", "9:16", "1:1"] | None',
        "duration": 'int | None',
        "watermark": 'bool | None',
        "seed": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


# Request schema for HappyHorse 1.0 text-to-video generation.
HappyHorseT2VRequest = TypedDict(
    "HappyHorseT2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "resolution": 'Literal["720P", "1080P"] | None',
        "ratio": 'Literal["16:9", "9:16", "1:1"] | None',
        "duration": 'int | None',
        "watermark": 'bool | None',
        "seed": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


# Request schema for HappyHorse 1.0 instruction-based video editing.
HappyHorseVideoEditRequest = TypedDict(
    "HappyHorseVideoEditRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "video_url": 'Required[str]',
        "images": 'list[str] | None',
        "resolution": 'Literal["720P", "1080P"] | None',
        "watermark": 'bool | None',
        "audio_setting": 'Literal["auto", "origin"] | None',
        "seed": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class HappyHorseVideoEditResponse(TypedDict, total=False):
    """Response schema for HappyHorse 1.0 Video-Edit."""

    urls: Required[list[str]]
    model: Required[str]
    resolution: str | None
    duration: float | None
    task_id: str | None
    task_address: str | None
    mode: str | None


class HappyHorseVideoResponse(TypedDict, total=False):
    """Response schema for HappyHorse 1.0 T2V/I2V/R2V routes."""

    urls: Required[list[str]]
    model: Required[str]
    resolution: str | None
    duration: int | None
    task_id: str | None
    task_address: str | None
    mode: str | None


class ImageInfo(TypedDict, total=False):
    """ImageInfo"""

    name: Required[str]
    description: str
    os: str | None
    includes: list[str]
    service_modes: list[str]


class ImagesResponse(TypedDict, total=False):
    """ImagesResponse"""

    images: Required[list[ImageInfo]]
    count: Required[int]


# IndexTTS-2 text-to-speech request (audio source, direct mode only).
IndexTts2Request = TypedDict(
    "IndexTts2Request",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "input": 'Required[str]',
        "voice": 'str | None',
        "spk_audio_url": 'str | None',
        "emo_audio_url": 'str | None',
        "sample_rate": 'int | None',
        "speed": 'float | None',
        "gain": 'float | None',
        "emo_control_method": 'Literal[0, 1, 2, 3] | None',
        "emo_alpha": 'float | None',
        "emo_vec": 'list[float] | None',
        "emo_text": 'str | None',
        "use_random": 'bool | None',
        "interval_silence": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class IndexTts2Response(TypedDict, total=False):
    """Response schema for index-tts-2: the audio comes back inline, base64-encoded."""

    audio_base64: Required[str]
    content_type: str | None
    task_id: str | None
    mode: str | None


class InstanceAccepted(TypedDict, total=False):
    """InstanceAccepted"""

    id: Required[str]
    status: Required[str]


class InstanceList(TypedDict, total=False):
    """InstanceList"""

    instances: Required[list[InstanceView]]
    count: Required[int]
    total: Required[int]
    has_more: Required[bool]
    next_cursor: str | None
    wallet: WalletStatus | None


class InstanceRequest(TypedDict, total=False):
    """`POST /v2/instances` body. Nothing about the hardware is tunable: there is"""

    prescription: Required[str]
    image: Required[str]
    ssh_public_key: Required[str]
    service_mode: str | None
    billing_mode: str | None
    region: str | None
    max_lifetime_hours: float | None
    webhook_url: str | None


class InstanceUsageResponse(TypedDict, total=False):
    """InstanceUsageResponse"""

    instances: Required[list[UsageRow]]
    totals: Required[UsageTotals]
    window: Required[UsageWindow]
    currency: str


class InstanceView(TypedDict, total=False):
    """InstanceView"""

    id: Required[str]
    status: Required[Literal["requested", "provisioning", "ready", "terminating", "terminated", "failed"]]
    prescription: Required[str]
    display_name: str | None
    kind: str | None
    image: Required[str]
    service_mode: Required[str]
    billing_mode: Required[str]
    billing_period_seconds: int | None
    rate_per_period: float | None
    region: str | None
    connection: DedicatedConnection | ContainerConnection | None
    ssh_key_fingerprint: str | None
    expires_at: str | None
    ended_reason: str | None
    created_at: Required[str]
    ready_at: str | None
    terminate_requested_at: str | None
    ended_at: str | None
    hours_billed: float
    spend_usd: float
    webhook_url: str | None


class InstanceWebhookPayload(TypedDict, total=False):
    """The JSON body POSTed to an instance's `webhook_url`."""

    event: Required[str]
    task_id: Required[str]
    status: Required[str]
    elapsed_seconds: Required[int]
    task_address: str | None
    mode: Required[str]
    model: Required[str]
    created_at: Required[str]
    result: dict[str, Any] | None
    result_omitted: bool | None


class KeyAnalytics(TypedDict, total=False):
    """KeyAnalytics"""

    lifetime: dict[str, Any] | None
    by_date: dict[str, Any] | None


class KeyBudgetTopupRequest(TypedDict, total=False):
    """KeyBudgetTopupRequest"""

    amount: Required[float]


class KeyBudgetTopupResponse(TypedDict, total=False):
    """KeyBudgetTopupResponse"""

    status: Required[str]
    key: Required[str]
    key_id: str | None
    previous_budget: float | None
    new_budget: Required[float]
    amount_added: Required[float]


class KeyListResponse(TypedDict, total=False):
    """KeyListResponse"""

    total: Required[int]
    max_allowed: Required[int]
    limit: Required[int]
    has_more: Required[bool]
    next_cursor: str | None
    keys: Required[list[KeyResponse]]


# Rate limit restrictions for a key (must be <= tier limits)
KeyRateLimits = TypedDict(
    "KeyRateLimits",
    {
        "opengpu": 'int | None',
        "direct": 'int | None',
        "global": 'int | None',
    },
    total=False,
)


class KeyResponse(TypedDict, total=False):
    """KeyResponse"""

    key: Required[str]
    key_id: str | None
    name: Required[str]
    status: Required[str]
    created_at: Required[str]
    last_used_at: Required[str | None]
    restrictions: Required[dict[str, Any]]
    key_budget: float | None
    is_superkey: bool
    system: bool


class KeyRestrictions(TypedDict, total=False):
    """Key-level restrictions to add on top of tier restrictions."""

    model_restrictions: list[str] | None
    rate_limits: KeyRateLimits | None


class KeyWithAnalytics(TypedDict, total=False):
    """KeyWithAnalytics"""

    key: Required[str]
    key_id: str | None
    name: Required[str]
    status: Required[str]
    created_at: Required[str]
    last_used_at: Required[str | None]
    analytics: Required[KeyAnalytics]
    key_budget: float | None
    is_superkey: bool
    system: bool


# Request schema for Kling image-to-video generation.
KlingI2VRequest = TypedDict(
    "KlingI2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "image": 'Required[str]',
        "image_tail": 'str | None',
        "aspect_ratio": 'Literal["16:9", "9:16", "1:1"] | None',
        "duration": 'Literal[5, 10] | None',
        "negative_prompt": 'str | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class KlingI2VResponse(TypedDict, total=False):
    """Response schema for Kling image-to-video generation"""

    urls: Required[list[str]]
    model: str
    aspect_ratio: str | None
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Kling O1 video generation (text-to-video with optional
KlingO1Request = TypedDict(
    "KlingO1Request",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "aspect_ratio": 'Literal["16:9", "9:16", "1:1"] | None',
        "duration": 'Literal[5, 10] | None',
        "quality_mode": 'Literal["std", "pro"] | None',
        "first_frame_url": 'str | None',
        "end_frame_url": 'str | None',
        "base_video_url": 'str | None',
        "base_video_keep_audio": 'bool | None',
        "reference_video_url": 'str | None',
        "reference_video_keep_audio": 'bool | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class KlingO1Response(TypedDict, total=False):
    """Response schema for Kling O1 video generation"""

    urls: Required[list[str]]
    model: str
    aspect_ratio: str | None
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Kling text-to-video generation.
KlingT2VRequest = TypedDict(
    "KlingT2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "aspect_ratio": 'Literal["16:9", "9:16", "1:1"] | None',
        "duration": 'Literal[5, 10] | None',
        "negative_prompt": 'str | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class KlingT2VResponse(TypedDict, total=False):
    """Response schema for Kling text-to-video generation"""

    urls: Required[list[str]]
    model: str
    aspect_ratio: str | None
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Kling v3 image-to-video generation.
KlingV3I2VRequest = TypedDict(
    "KlingV3I2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "image": 'Required[str]',
        "image_tail": 'str | None',
        "aspect_ratio": 'Literal["16:9", "9:16", "1:1"] | None',
        "duration": 'int | None',
        "quality_mode": 'Literal["std", "pro"] | None',
        "sound": 'bool | None',
        "negative_prompt": 'str | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class KlingV3I2VResponse(TypedDict, total=False):
    """Response schema for Kling v3 image-to-video generation"""

    urls: Required[list[str]]
    model: str
    aspect_ratio: str | None
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Kling v3 motion control: a character image, a
KlingV3MotionControlRequest = TypedDict(
    "KlingV3MotionControlRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "image_url": 'Required[str]',
        "video_url": 'Required[str]',
        "character_orientation": 'Required[Literal["image", "video"]]',
        "quality_mode": 'Literal["std", "pro"] | None',
        "prompt": 'str | None',
        "duration": 'Literal[5, 10] | None',
        "aspect_ratio": 'Literal["16:9", "9:16", "1:1"] | None',
        "keep_original_sound": 'bool | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class KlingV3MotionControlResponse(TypedDict, total=False):
    """Response schema for Kling v3 motion-control video generation"""

    urls: Required[list[str]]
    model: str
    aspect_ratio: str | None
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Kling v3 text-to-video generation.
KlingV3T2VRequest = TypedDict(
    "KlingV3T2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "aspect_ratio": 'Literal["16:9", "9:16", "1:1"] | None',
        "duration": 'int | None',
        "quality_mode": 'Literal["std", "pro"] | None',
        "sound": 'bool | None',
        "negative_prompt": 'str | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class KlingV3T2VResponse(TypedDict, total=False):
    """Response schema for Kling v3 text-to-video generation"""

    urls: Required[list[str]]
    model: str
    aspect_ratio: str | None
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


class LastSpawn(TypedDict, total=False):
    """How the last attempt on this row went, across all customers — Relay's"""

    outcome: Required[str]
    at: str | None
    reason: str | None


class Lifetime(TypedDict, total=False):
    """Present only when the row's provider caps how long an instance may"""

    default_hours: Required[float]
    max_hours: Required[float]


# Request schema for Decart Lucy 2.5 text-directed video editing
Lucy25Request = TypedDict(
    "Lucy25Request",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "video_url": 'Required[str]',
        "prompt": 'str | None',
        "seed": 'int | None',
        "resolution": 'Literal["720p"] | None',
        "enhance_prompt": 'bool | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
        "reference_image_url": 'str | None',
        "self_anchor": 'bool | None',
    },
    total=False,
)


class LucyVideoResponse(TypedDict, total=False):
    """Response schema for Decart Lucy video-to-video routes."""

    urls: Required[list[str]]
    model: Required[str]
    resolution: str | None
    duration: float | None
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Decart Lucy VTON 3 virtual try-on.
LucyVton3Request = TypedDict(
    "LucyVton3Request",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "video_url": 'Required[str]',
        "prompt": 'str | None',
        "seed": 'int | None',
        "resolution": 'Literal["720p"] | None',
        "enhance_prompt": 'bool | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
        "reference_image_url": 'str | None',
    },
    total=False,
)


class MediaStoragePricing(TypedDict, total=False):
    """Per-file fee for keeping an output on Relay's CDN."""

    relay1d: float | None
    relay7d: float | None
    relay30d: float | None
    unit: str


class MetricsBucket(TypedDict, total=False):
    """MetricsBucket"""

    object: str
    start_time: Required[int]
    end_time: Required[int]
    results: Required[list[MetricsResult]]


class MetricsPage(TypedDict, total=False):
    """MetricsPage"""

    object: str
    data: Required[list[MetricsBucket]]
    summary: MetricsSummary | None
    has_more: Required[bool]
    next_page: str | None


class MetricsResult(TypedDict, total=False):
    """One metrics row within a bucket."""

    request_count: Required[int]
    success_count: Required[int]
    error_count: Required[int]
    user_error_count: Required[int]
    upstream_error_count: Required[int]
    unclassified_error_count: Required[int]
    latency_ms: Required[PercentileSet]
    provider_latency_ms: Required[PercentileSet]
    ttft_ms: Required[PercentileSet]
    model: str
    source: str
    mode: str
    key_id: str | None
    key_name: str | None


class MetricsSummary(TypedDict, total=False):
    """Whole-range rollup (all buckets, all pages) — same row shape as a bucket,"""

    object: str
    start_time: Required[int]
    end_time: Required[int]
    results: Required[list[MetricsResult]]


# MiniMax speech-2.8-hd text-to-speech request (audio source, direct mode only).
MinimaxSpeech28HdRequest = TypedDict(
    "MinimaxSpeech28HdRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "text": 'Required[str]',
        "voice_id": 'Required[str]',
        "speed": 'float | None',
        "vol": 'float | None',
        "pitch": 'int | None',
        "emotion": 'Literal["happy", "sad", "angry", "fearful", "disgusted", "surprised", "calm", "fluent"] | None',
        "audio_format": 'Literal["mp3", "pcm", "flac", "wav"] | None',
        "audio_sample_rate": 'Literal[8000, 16000, 22050, 24000, 32000, 44100] | None',
        "audio_bitrate": 'Literal[32000, 64000, 128000, 256000] | None',
        "audio_channel": 'Literal[1, 2] | None',
        "language_boost": 'str | None',
        "subtitle_enable": 'bool | None',
        "aigc_watermark": 'bool | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class MinimaxSpeech28HdResponse(TypedDict, total=False):
    """Response schema for minimax speech-2.8-hd: inline base64 audio plus encoding facts."""

    audio_base64: Required[str]
    content_type: str | None
    task_id: str | None
    mode: str | None
    audio_length_ms: int | None
    audio_format: str | None
    audio_size_bytes: int | None
    audio_sample_rate: int | None
    audio_channel: int | None


class ModelAllowlistResponse(TypedDict, total=False):
    """ModelAllowlistResponse"""

    status: Required[str]
    model_allowlist: list[str] | None
    updated_at: Required[str]


class ModelAllowlistView(TypedDict, total=False):
    """Read side of the allowlist — just the current value (no write-oriented"""

    model_allowlist: list[str] | None


class ModelDetail(TypedDict, total=False):
    """`GET /v2/models/{model}` — one model: where it runs, its route, its list prices."""

    name: Required[str]
    display_name: str | None
    tag: str | None
    modes: Required[list[Literal["auto", "direct", "opengpu"]]]
    sources: Required[list[str]]
    endpoint: Required[ModelEndpoint | None]
    request_schema: Required[dict[str, Any] | None]
    request_schema_url: Required[str | None]
    request_example: Required[dict[str, Any] | None]
    response_schema: Required[dict[str, Any] | None]
    response_schema_url: Required[str | None]
    store_output_supported: Required[bool]
    restricted_tiers: Required[list[str]]
    pricing: Required[list[PricingItem]]
    available: Required[bool]
    status: Required[Literal["available", "retired"]]


class ModelEndpoint(TypedDict, total=False):
    """The one route that serves a model, and how to call it."""

    method: Required[str]
    path: Required[str]
    operation_id: Required[str]
    model_in_body: Required[bool]
    model_default: str | None
    async_default: Required[bool]
    streams: Required[bool]


class ModelRow(TypedDict, total=False):
    """One model as `GET /v2/models` lists it (documentation only — the route"""

    name: Required[str]
    tag: Required[str]
    store_output_supported: Required[bool]
    display_name: str | None
    endpoint: Required[ModelEndpoint | None]


class ModelsResponse(TypedDict, total=False):
    """`GET /v2/models` — models grouped by mode, then by source."""

    auto: Required[dict[str, list[ModelRow]]]
    direct: dict[str, list[ModelRow]] | None
    opengpu: dict[str, list[ModelRow]] | None
    model_restrictions_per_tier: Required[dict[str, list[str]]]


class NetworkSpec(TypedDict, total=False):
    """NetworkSpec"""

    download_mbps: Required[int]
    upload_mbps: Required[int]


class NpuSpec(TypedDict, total=False):
    """NpuSpec"""

    model: Required[str]
    count: Required[int]
    memory_gb: int | None


class OpenAIChatCompletionChunk(TypedDict, total=False):
    """One `chat.completion.chunk` frame. `choices[].delta` carries the incremental token(s); the final frame before `[DONE]` carries `usage` when `stream_options.include_usage=true`."""

    id: str
    object: str
    choices: list[dict[str, Any]]
    usage: dict[str, Any] | None


# OpenAI Chat Completions API request
OpenAIChatRequest = TypedDict(
    "OpenAIChatRequest",
    {
        "model": 'Required[str]',
        "messages": 'Required[list[dict[str, Any]]]',
        "max_tokens": 'int | None',
        "max_completion_tokens": 'int | None',
        "temperature": 'float | None',
        "top_p": 'float | None',
        "frequency_penalty": 'float | None',
        "presence_penalty": 'float | None',
        "stop": 'str | list[str] | None',
        "stream": 'bool | None',
        "response_format": 'dict[str, Any] | None',
        "seed": 'int | None',
        "tools": 'list[dict[str, Any]] | None',
        "tool_choice": 'str | dict[str, Any] | None',
        "n": 'int | None',
        "logprobs": 'bool | None',
        "top_logprobs": 'int | None',
        "user": 'str | None',
        "stream_options": 'dict[str, Any] | None',
        "store": 'bool | None',
        "chat_template_kwargs": 'dict[str, Any] | None',
        "top_k": 'int | None',
        "min_p": 'float | None',
        "repetition_penalty": 'float | None',
        "logit_bias": 'dict[str, Any] | None',
        "reasoning_effort": 'Literal["none", "low", "medium", "high", "xhigh", "max"] | None',
        "reasoning": 'dict[str, Any] | None',
        "include_reasoning": 'bool | None',
        "structured_outputs": 'bool | None',
        "mode": 'Literal["auto", "opengpu", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class OpenAIChatResponse(TypedDict, total=False):
    """OpenAI Chat Completions API response"""

    id: str | None
    object: str
    created: int | None
    model: Required[str]
    choices: Required[list[dict[str, Any]]]
    usage: dict[str, Any] | None
    system_fingerprint: str | None
    task_id: str | None
    task_address: str | None
    mode: str | None


class PercentileSet(TypedDict, total=False):
    """p50/p90/p95/p99 (ms) + the `sample_count` they rest on. A percentile is"""

    p50: float | None
    p90: float | None
    p95: float | None
    p99: float | None
    sample_count: int


class PricingItem(TypedDict, total=False):
    """Pricing for a single mode/model combination"""

    mode: Required[str]
    model: Required[str]
    billing_type: Required[str]
    per_1m_input_tokens: float | None
    per_1m_output_tokens: float | None
    per_1m_cached_input_tokens: float | None
    per_image: float | None
    per_image_resolution: dict[str, Any] | None
    per_1k_characters: float | None
    per_second_audio: float | None
    per_second_video: dict[str, Any] | None
    per_1m_media_input_tokens: float | dict[str, float] | None
    per_1m_media_output_tokens: float | dict[str, float] | None
    context_tier_threshold: int | None
    per_1m_input_tokens_long: float | None
    per_1m_output_tokens_long: float | None
    per_1m_cached_input_tokens_long: float | None
    per_1m_cache_write_5m_input_tokens: float | None
    per_1m_cache_write_1h_input_tokens: float | None
    per_1m_cache_write_5m_input_tokens_long: float | None
    per_1m_cache_write_1h_input_tokens_long: float | None


class PricingResponse(TypedDict, total=False):
    """Public pricing information"""

    pricing: Required[list[PricingItem]]
    total_count: Required[int]
    media_storage: MediaStoragePricing | None


class ProfileResponse(TypedDict, total=False):
    """ProfileResponse"""

    customer_id: Required[str]
    name: Required[str]
    email: str | None
    email_verified: Required[bool]
    tier: Required[str]
    status: Required[str]
    created_at: Required[str]
    credits: Required[dict[str, Any]]
    tier_details: Required[dict[str, Any]]
    sub_key_model_allowlist: list[str] | None
    warning_threshold: float


class PromoBalance(TypedDict, total=False):
    """PromoBalance"""

    promo_id: Required[str]
    balance: Required[float]
    initial_balance: Required[float]
    valid_for: list[str] | None
    expires_at: str | None
    granted_at: Required[str]


class PromoteKeyResponse(TypedDict, total=False):
    """PromoteKeyResponse"""

    status: Required[str]
    key: Required[str]
    key_id: str | None
    message: str


# Qwen3-TTS-Flash text-to-speech request (audio source, direct mode only).
Qwen3TtsFlashRequest = TypedDict(
    "Qwen3TtsFlashRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "input": 'Required[str]',
        "voice": 'Required[str]',
        "language_type": 'Literal["Chinese", "English", "German", "Italian", "Portuguese", "Spanish", "Japanese", "Korean", "French", "Russian", "Auto"] | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class Qwen3TtsFlashResponse(TypedDict, total=False):
    """Response schema for qwen3-tts-flash: the audio comes back as a hosted link."""

    audio_url: Required[str]
    characters: int | None
    audio_id: str | None
    task_id: str | None
    mode: str | None


# Request schema for Qwen image editing.
QwenEditRequest = TypedDict(
    "QwenEditRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "image": 'Required[str]',
        "model": 'str | None',
        "size": 'str | None',
        "seed": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class QwenEditResponse(TypedDict, total=False):
    """Response schema for Qwen image editing"""

    urls: Required[list[str]]
    model: Required[str]
    size: Required[str]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Qwen text-to-image generation.
QwenImageRequest = TypedDict(
    "QwenImageRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "model": 'str | None',
        "size": 'str | None',
        "seed": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class QwenImageResponse(TypedDict, total=False):
    """Response schema for Qwen image generation"""

    urls: Required[list[str]]
    model: Required[str]
    size: Required[str]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Real-ESRGAN image upscaling.
RealESRGANUpscaleRequest = TypedDict(
    "RealESRGANUpscaleRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "image_url": 'str | None',
        "image_b64": 'str | None',
        "model": 'Literal["TencentARC/RealESRGAN-x4plus", "TencentARC/RealESRGAN-x2plus", "TencentARC/RealESRGAN-x4plus-anime"] | None',
        "output_format": 'Literal["png", "jpeg", "jpg", "webp"] | None',
        "mode": 'Literal["auto", "opengpu", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class RealESRGANUpscaleResponse(TypedDict, total=False):
    """Response schema for Real-ESRGAN image upscaling."""

    images: Required[list[str]]
    model: Required[str]
    width: int | None
    height: int | None
    scale: int | None
    task_id: str | None
    task_address: str | None
    mode: str | None


class RelayError(TypedDict, total=False):
    """Machine-readable error object. `code`, `type` and `source` are all null on a raise site that has not been classified yet."""

    code: Required[str | None]
    type: Required[Literal["authentication", "authorization", "internal", "rate_limit", "removed", "schema", "timeout", "unavailable", "validation"] | None]
    source: Required[Literal["client", "provider", "relay"] | None]
    message: Required[str]
    request_id: Required[str | None]
    detail: Any


class RelayErrorResponse(TypedDict, total=False):
    """Every error body: the legacy `detail` plus the `error` object."""

    detail: Required[str | list[ValidationError] | dict[str, Any]]
    error: Required[RelayError]


# Request schema for Seedream image generation and reference-image editing.
SeedreamRequest = TypedDict(
    "SeedreamRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "model": 'str | None',
        "images": 'list[str] | None',
        "size": 'str',
        "watermark": 'bool | None',
        "output_format": 'Literal["png", "jpeg"] | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class SeedreamResponse(TypedDict, total=False):
    """Response schema for Seedream image generation."""

    urls: Required[list[str]]
    model: Required[str]
    size: Required[str]
    task_id: str | None
    mode: str | None


# Request schema for Sora image-to-video generation.
SoraI2VRequest = TypedDict(
    "SoraI2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "first_frame_url": 'Required[str]',
        "prompt": 'str | None',
        "duration": 'Literal[4, 8, 12] | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class SoraI2VResponse(TypedDict, total=False):
    """Response schema for Sora image-to-video generation"""

    videos: Required[list[str]]
    model: str
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Sora Pro image-to-video generation.
SoraProI2VRequest = TypedDict(
    "SoraProI2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "first_frame_url": 'Required[str]',
        "prompt": 'str | None',
        "resolution": 'Literal["720p", "1080p"] | None',
        "duration": 'Literal[4, 8, 12] | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class SoraProI2VResponse(TypedDict, total=False):
    """Response schema for Sora Pro image-to-video generation"""

    videos: Required[list[str]]
    model: str
    resolution: str | None
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Sora Pro text-to-video generation.
SoraProT2VRequest = TypedDict(
    "SoraProT2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "size": 'Literal["720x1280", "1280x720", "1024x1792", "1792x1024"] | None',
        "duration": 'Literal[4, 8, 12] | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class SoraProT2VResponse(TypedDict, total=False):
    """Response schema for Sora Pro text-to-video generation"""

    videos: Required[list[str]]
    model: str
    size: str | None
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Sora text-to-video generation.
SoraT2VRequest = TypedDict(
    "SoraT2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "size": 'Literal["720x1280", "1280x720"] | None',
        "duration": 'Literal[4, 8, 12] | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class SoraT2VResponse(TypedDict, total=False):
    """Response schema for Sora text-to-video generation"""

    videos: Required[list[str]]
    model: str
    size: str | None
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


class StreamErrorResponseError(TypedDict, total=False):
    message: Required[str]
    type: Required[str]
    code: int


class StreamErrorResponse(TypedDict, total=False):
    """Error body of a `stream: true` request that failed before its first chunk."""

    error: Required[StreamErrorResponseError]


class TaskStatusResponse(TypedDict, total=False):
    """Response from GET /v2/tasks/{task_id} polling endpoint."""

    task_id: Required[str]
    status: Required[Literal["queued", "running", "completed", "failed"]]
    elapsed_seconds: Required[int]
    task_address: str | None
    mode: str | None
    model: str | None
    created_at: str | None
    result: dict[str, Any] | None
    error: str | None
    error_code: str | None
    error_detail: dict[str, Any] | None


class TerminateResponse(TypedDict, total=False):
    """TerminateResponse"""

    id: Required[str]
    status: Required[str]


class TierInfo(TypedDict, total=False):
    """Tier information from database"""

    tier: Required[str]
    model_restrictions: Required[list[str]]
    rate_limits: Required[dict[str, Any]]
    max_keys: Required[int]


class TiersResponse(TypedDict, total=False):
    """All tiers with current tier"""

    tiers: Required[list[TierInfo]]
    current_tier: Required[str]


class UpdateKeyRequest(TypedDict, total=False):
    """UpdateKeyRequest"""

    name: str | None
    restrictions: KeyRestrictions | None
    key_budget: float | None


class UpdateModelAllowlistRequest(TypedDict, total=False):
    """Set the customer-wide allowlist applied to non-superkey sub-keys."""

    model_allowlist: list[str] | None


class UpdateProfileRequest(TypedDict, total=False):
    """UpdateProfileRequest"""

    name: str | None


class UpdateProfileResponse(TypedDict, total=False):
    """UpdateProfileResponse"""

    status: Required[str]
    updated_fields: Required[list[str]]


# UsageQueryInfo
UsageQueryInfo = TypedDict(
    "UsageQueryInfo",
    {
        "period": 'str | None',
        "from": 'str | None',
        "to": 'str | None',
    },
    total=False,
)


class UsageRow(TypedDict, total=False):
    """UsageRow"""

    id: Required[str]
    prescription: Required[str]
    service_mode: Required[str]
    billing_mode: Required[str]
    periods: Required[int]
    hours: Required[float]
    rate: float | None
    spend: Required[float]
    first_period_start: str | None
    last_period_start: str | None


class UsageTimeseriesBucket(TypedDict, total=False):
    """UsageTimeseriesBucket"""

    object: str
    start_time: Required[int]
    end_time: Required[int]
    results: Required[list[UsageTimeseriesResult]]


class UsageTimeseriesPage(TypedDict, total=False):
    """UsageTimeseriesPage"""

    object: str
    data: Required[list[UsageTimeseriesBucket]]
    summary: UsageTimeseriesSummary | None
    has_more: Required[bool]
    next_page: str | None


class UsageTimeseriesResult(TypedDict, total=False):
    """One cost/usage row within a bucket (for /usage/timeseries)."""

    request_count: Required[int]
    cost_usd: Required[float]
    input_tokens: Required[int]
    output_tokens: Required[int]
    cached_input_tokens: Required[int]
    media_input_tokens: int
    media_output_tokens: int
    model: str
    source: str
    mode: str
    key_id: str | None
    key_name: str | None


class UsageTimeseriesSummary(TypedDict, total=False):
    """Whole-range cost/token rollup (all buckets, all pages) — the total spend"""

    object: str
    start_time: Required[int]
    end_time: Required[int]
    results: Required[list[UsageTimeseriesResult]]


class UsageTotals(TypedDict, total=False):
    """UsageTotals"""

    instances: Required[int]
    periods: Required[int]
    hours: Required[float]
    spend: Required[float]


# UsageWindow
UsageWindow = TypedDict(
    "UsageWindow",
    {
        "from": 'str | None',
        "to": 'str | None',
    },
    total=False,
)


class ValidationError(TypedDict, total=False):
    """ValidationError"""

    loc: Required[list[str | int]]
    msg: Required[str]
    type: Required[str]


# Request schema for Google Veo 3.1 Fast video generation.
VeoFastRequest = TypedDict(
    "VeoFastRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "first_frame_url": 'str | None',
        "negative_prompt": 'str | None',
        "aspect_ratio": 'Literal["16:9", "9:16"] | None',
        "resolution": 'Literal["720p", "1080p", "4k"] | None',
        "duration": 'Literal[4, 6, 8] | None',
        "seed": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class VeoFastResponse(TypedDict, total=False):
    """Response schema for Google Veo 3.1 Fast video generation."""

    urls: Required[list[str]]
    model: str
    resolution: str | None
    duration: int | None
    task_id: str | None
    task_address: str | None
    mode: str | None


class WalletStatus(TypedDict, total=False):
    """Your real balance (promo credits never count) and how many hours it"""

    balance: Required[float]
    warning_threshold: float | None
    grace_started_at: str | None
    grace_ends_at: str | None
    hours_left: float | None


# Request schema for Wan 2.6 image-to-video generation.
Wan26I2VRequest = TypedDict(
    "Wan26I2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "first_frame_url": 'Required[str]',
        "resolution": 'Literal["720P", "1080P"] | None',
        "duration": 'Literal[5, 10, 15] | None',
        "negative_prompt": 'str | None',
        "audio_url": 'str | None',
        "prompt_extend": 'bool | None',
        "seed": 'int | None',
        "shot_type": 'Literal["single", "multi"] | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class Wan26I2VResponse(TypedDict, total=False):
    """Response schema for Wan 2.6 image-to-video generation"""

    urls: Required[list[str]]
    model: str
    resolution: str | None
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Wan 2.6 text-to-video generation.
Wan26T2VRequest = TypedDict(
    "Wan26T2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "size": 'Literal["1280x720", "720x1280", "1920x1080", "1080x1920"] | None',
        "duration": 'Literal[5, 10, 15] | None',
        "negative_prompt": 'str | None',
        "audio_url": 'str | None',
        "prompt_extend": 'bool | None',
        "seed": 'int | None',
        "shot_type": 'Literal["single", "multi"] | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class Wan26T2VResponse(TypedDict, total=False):
    """Response schema for Wan 2.6 text-to-video generation"""

    urls: Required[list[str]]
    model: str
    size: str | None
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Wan image-to-video generation.
WanI2VRequest = TypedDict(
    "WanI2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "first_frame_url": 'Required[str]',
        "resolution": 'Literal["480p", "720p", "1080p"] | None',
        "duration": 'Literal[5, 10] | None',
        "negative_prompt": 'str | None',
        "audio_url": 'str | None',
        "enable_prompt_expansion": 'bool | None',
        "seed": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class WanI2VResponse(TypedDict, total=False):
    """Response schema for Wan image-to-video generation"""

    videos: Required[list[str]]
    model: str
    resolution: Required[str]
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


# Request schema for Wan 2.7 Image Pro — see the route for the three
WanImageRequest = TypedDict(
    "WanImageRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'str | None',
        "model": 'str | None',
        "image": 'str | None',
        "images": 'list[str] | None',
        "size": 'str | None',
        "n": 'int | None',
        "seed": 'int | None',
        "watermark": 'bool | None',
        "thinking_mode": 'bool | None',
        "enable_sequential": 'bool | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class WanImageResponse(TypedDict, total=False):
    """Response schema for Wan2.7 image generation."""

    urls: Required[list[str]]
    model: Required[str]
    size: str | None
    task_id: str | None
    mode: str | None


# Request schema for Wan text-to-video generation.
WanT2VRequest = TypedDict(
    "WanT2VRequest",
    {
        "store_output": 'Literal["provider", "relay1d", "relay7d", "relay30d"] | None',
        "prompt": 'Required[str]',
        "model": 'str | None',
        "size": 'Literal["832x480", "480x832", "1280x720", "720x1280"] | None',
        "duration": 'Literal[5, 10] | None',
        "negative_prompt": 'str | None',
        "audio_url": 'str | None',
        "prompt_extend": 'bool | None',
        "seed": 'int | None',
        "mode": 'Literal["auto", "direct"] | None',
        "async": 'bool | None',
        "webhook_url": 'str | None',
    },
    total=False,
)


class WanT2VResponse(TypedDict, total=False):
    """Response schema for Wan text-to-video generation"""

    videos: Required[list[str]]
    model: Required[str]
    size: Required[str]
    duration: Required[int]
    task_id: str | None
    task_address: str | None
    mode: str | None


class WebhookDeliveryAttempt(TypedDict, total=False):
    """WebhookDeliveryAttempt"""

    attempt: Required[int]
    at: int | None
    outcome: Required[str]
    status_code: int | None
    error: str | None


class WebhookDeliveryDetail(TypedDict, total=False):
    """WebhookDeliveryDetail"""

    task_id: Required[str]
    webhook_id: Required[str]
    url: Required[str]
    event: Required[str]
    last_outcome: Required[str]
    final: bool
    attempt_count: Required[int]
    first_attempt_at: int | None
    last_attempt_at: int | None
    attempts: Required[list[WebhookDeliveryAttempt]]


class WebhookDeliveryItem(TypedDict, total=False):
    """One webhook delivery (one async task's callback) — thin header row;"""

    task_id: Required[str]
    webhook_id: Required[str]
    url: Required[str]
    event: Required[str]
    last_outcome: Required[str]
    final: bool
    attempt_count: Required[int]
    first_attempt_at: int | None
    last_attempt_at: int | None


class WebhookDeliveryPage(TypedDict, total=False):
    """WebhookDeliveryPage"""

    object: str
    data: Required[list[WebhookDeliveryItem]]
    has_more: Required[bool]
    next_page: str | None


class WebhookPayload(TypedDict, total=False):
    """The JSON body POSTed to your `webhook_url` when an async task reaches a"""

    event: Required[Literal["task.completed", "task.failed"]]
    task_id: Required[str]
    status: Required[str]
    elapsed_seconds: Required[int]
    model: str | None
    mode: str | None
    created_at: str | None
    task_address: str | None
    result: dict[str, Any] | None
    error: str | None
    error_code: str | None
    error_detail: dict[str, Any] | None
    result_omitted: bool | None


class WebhookSecretResponse(TypedDict, total=False):
    """Your webhook signing secret. Retrievable at any time; created on first read."""

    secret: Required[str]
    created_at: Required[str]
    previous_valid_until: str | None


class WorkflowListResponse(TypedDict, total=False):
    """WorkflowListResponse"""

    workflows: Required[list[WorkflowTemplateItem]]
    total: Required[int]


class WorkflowRunAccepted(TypedDict, total=False):
    """WorkflowRunAccepted"""

    run_id: Required[str]
    status: Required[Literal["queued"]]
    poll_url: Required[str]


class WorkflowRunRequest(TypedDict, total=False):
    """WorkflowRunRequest"""

    inputs: dict[str, Any]
    store_output: Literal["provider", "relay1d", "relay7d", "relay30d"] | None
    webhook_url: str | None


class WorkflowRunState(TypedDict, total=False):
    """WorkflowRunState"""

    run_id: Required[str]
    workflow_id: Required[str]
    version: Required[int]
    status: Required[Literal["queued", "running", "completed", "failed", "cancelled"]]
    steps: Required[list[WorkflowRunStepState]]
    inputs: Required[dict[str, Any]]
    store_output: str | None
    output: Any
    error: str | None
    failed_step_index: int | None
    total_cost_usd: float | None
    created_at: str | None
    completed_at: str | None


class WorkflowRunStepState(TypedDict, total=False):
    """WorkflowRunStepState"""

    step_index: Required[int]
    step_id: Required[str]
    model: Required[str]
    status: Required[Literal["pending", "submitted", "completed", "failed", "skipped"]]
    task_id: str | None
    output: Any
    error: str | None
    cost_usd: float | None


class WorkflowRunWebhookPayload(TypedDict, total=False):
    """The JSON body POSTed to a run's `webhook_url` when the run ends (U5)."""

    event: Required[Literal["workflow.completed", "workflow.failed"]]
    task_id: Required[str]
    status: Required[Literal["completed"]]
    elapsed_seconds: Required[int]
    task_address: str | None
    mode: Required[Literal["workflows"]]
    model: Required[str]
    created_at: Required[str]
    result: WorkflowRunState | None
    result_omitted: bool | None


class WorkflowStepSummary(TypedDict, total=False):
    """WorkflowStepSummary"""

    step_id: Required[str]
    model: Required[str]
    source: Required[str]
    endpoint: Required[str]


class WorkflowTemplateItem(TypedDict, total=False):
    """WorkflowTemplateItem"""

    workflow_id: Required[str]
    version: Required[int]
    name: Required[str]
    description: str | None
    input_schema: dict[str, Any] | None
    steps: Required[list[WorkflowStepSummary]]
    restricted_tiers: list[str]

__all__ = [
    "ASRRequest",
    "ASRResponse",
    "AnthropicMessagesRequest",
    "AnthropicMessagesResponse",
    "AnthropicStreamEvent",
    "AsyncTaskAccepted",
    "Availability",
    "BillingMode",
    "BillingTerms",
    "BriaVideoUpscaleRequest",
    "BriaVideoUpscaleResponse",
    "CatalogResponse",
    "CatalogRow",
    "ContainerConnection",
    "CpuSpec",
    "CreateKeyRequest",
    "CreateKeyResponse",
    "CreatedKeyRestrictions",
    "CreditHistoryResponse",
    "CreditTransaction",
    "CreditsResponse",
    "CustomerPricingItem",
    "CustomerPricingResponse",
    "CustomerSettingsResponse",
    "CustomerSettingsUpdate",
    "CustomerUsageResponse",
    "DedicatedConnection",
    "DoubaoSeedance15ProRequest",
    "DoubaoSeedance15ProResponse",
    "DoubaoSeedance20Request",
    "DoubaoSeedance20Response",
    "DoubaoSeedance25Request",
    "DoubaoSeedance25V2VRequest",
    "DoubaoSeedanceV2VRequest",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "FileListResponse",
    "FileResponse",
    "Flux1Request",
    "Flux1Response",
    "FluxRequest",
    "FluxResponse",
    "GeminiRequest",
    "GeminiResponse",
    "GptImage2Request",
    "GptImage2Response",
    "GptImageI2IRequest",
    "GptImageI2IResponse",
    "GptImageT2IRequest",
    "GptImageT2IResponse",
    "GpuSpec",
    "HappyHorse11T2VRequest",
    "HappyHorseI2VRequest",
    "HappyHorseR2VRequest",
    "HappyHorseT2VRequest",
    "HappyHorseVideoEditRequest",
    "HappyHorseVideoEditResponse",
    "HappyHorseVideoResponse",
    "ImageInfo",
    "ImagesResponse",
    "IndexTts2Request",
    "IndexTts2Response",
    "InstanceAccepted",
    "InstanceList",
    "InstanceRequest",
    "InstanceUsageResponse",
    "InstanceView",
    "InstanceWebhookPayload",
    "KeyAnalytics",
    "KeyBudgetTopupRequest",
    "KeyBudgetTopupResponse",
    "KeyListResponse",
    "KeyRateLimits",
    "KeyResponse",
    "KeyRestrictions",
    "KeyWithAnalytics",
    "KlingI2VRequest",
    "KlingI2VResponse",
    "KlingO1Request",
    "KlingO1Response",
    "KlingT2VRequest",
    "KlingT2VResponse",
    "KlingV3I2VRequest",
    "KlingV3I2VResponse",
    "KlingV3MotionControlRequest",
    "KlingV3MotionControlResponse",
    "KlingV3T2VRequest",
    "KlingV3T2VResponse",
    "LastSpawn",
    "Lifetime",
    "Lucy25Request",
    "LucyVideoResponse",
    "LucyVton3Request",
    "MediaStoragePricing",
    "MetricsBucket",
    "MetricsPage",
    "MetricsResult",
    "MetricsSummary",
    "MinimaxSpeech28HdRequest",
    "MinimaxSpeech28HdResponse",
    "ModelAllowlistResponse",
    "ModelAllowlistView",
    "ModelDetail",
    "ModelEndpoint",
    "ModelRow",
    "ModelsResponse",
    "NetworkSpec",
    "NpuSpec",
    "OpenAIChatCompletionChunk",
    "OpenAIChatRequest",
    "OpenAIChatResponse",
    "PercentileSet",
    "PricingItem",
    "PricingResponse",
    "ProfileResponse",
    "PromoBalance",
    "PromoteKeyResponse",
    "Qwen3TtsFlashRequest",
    "Qwen3TtsFlashResponse",
    "QwenEditRequest",
    "QwenEditResponse",
    "QwenImageRequest",
    "QwenImageResponse",
    "RealESRGANUpscaleRequest",
    "RealESRGANUpscaleResponse",
    "RelayError",
    "RelayErrorResponse",
    "SeedreamRequest",
    "SeedreamResponse",
    "SoraI2VRequest",
    "SoraI2VResponse",
    "SoraProI2VRequest",
    "SoraProI2VResponse",
    "SoraProT2VRequest",
    "SoraProT2VResponse",
    "SoraT2VRequest",
    "SoraT2VResponse",
    "StreamErrorResponse",
    "StreamErrorResponseError",
    "TaskStatusResponse",
    "TerminateResponse",
    "TierInfo",
    "TiersResponse",
    "UpdateKeyRequest",
    "UpdateModelAllowlistRequest",
    "UpdateProfileRequest",
    "UpdateProfileResponse",
    "UsageQueryInfo",
    "UsageRow",
    "UsageTimeseriesBucket",
    "UsageTimeseriesPage",
    "UsageTimeseriesResult",
    "UsageTimeseriesSummary",
    "UsageTotals",
    "UsageWindow",
    "ValidationError",
    "VeoFastRequest",
    "VeoFastResponse",
    "WalletStatus",
    "Wan26I2VRequest",
    "Wan26I2VResponse",
    "Wan26T2VRequest",
    "Wan26T2VResponse",
    "WanI2VRequest",
    "WanI2VResponse",
    "WanImageRequest",
    "WanImageResponse",
    "WanT2VRequest",
    "WanT2VResponse",
    "WebhookDeliveryAttempt",
    "WebhookDeliveryDetail",
    "WebhookDeliveryItem",
    "WebhookDeliveryPage",
    "WebhookPayload",
    "WebhookSecretResponse",
    "WorkflowListResponse",
    "WorkflowRunAccepted",
    "WorkflowRunRequest",
    "WorkflowRunState",
    "WorkflowRunStepState",
    "WorkflowRunWebhookPayload",
    "WorkflowStepSummary",
    "WorkflowTemplateItem",
]
