# GENERATED by scripts/unasync.py from relaygpu/_async/. Do not edit; edit the async source and rerun.
"""Text-to-speech and speech-to-text (port of src/audio.ts)."""

from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import TYPE_CHECKING, Any, cast

from ..types import KnownSpeechModel, KnownTranscribeModel, Mode, TaskProgress, UploadOptions
from .run import run

if TYPE_CHECKING:
    from .client import Relay


class Audio:
    """Text-to-speech and speech-to-text. Same options as the image helpers: an async answer (``async_=True``) is
    waited for."""

    def __init__(self, relay: Relay) -> None:
        self._relay = relay

    def _run(self, model: str, input: Mapping[str, Any], **options: Any) -> dict[str, Any]:
        """The one body of ``speech`` and ``transcribe``: ``run(..., wait=True)``, so never the 202 envelope."""
        return cast("dict[str, Any]", run(self._relay, model, input, wait=True, **options))

    def speech(
        self,
        model: KnownSpeechModel | str,
        input: Mapping[str, Any],
        *,
        on_progress: Callable[[TaskProgress], None] | None = None,
        timeout: float | None = None,
        mode: Mode | None = None,
        store_output: str | None = None,
        webhook_url: str | None = None,
        idempotency_key: str | None = None,
        async_: bool | None = None,
        upload: UploadOptions | None = None,
        inline_images: bool = False,
    ) -> dict[str, Any]:
        """Text-to-speech. Returns the response body: ``audio_url`` (a link that expires) or ``audio_base64`` +
        ``content_type``, per model."""
        return self._run(
            model,
            input,
            on_progress=on_progress,
            timeout=timeout,
            mode=mode,
            store_output=store_output,
            webhook_url=webhook_url,
            idempotency_key=idempotency_key,
            async_=async_,
            upload=upload,
            inline_images=inline_images,
        )

    def transcribe(
        self,
        model: KnownTranscribeModel | str,
        input: Mapping[str, Any],
        *,
        on_progress: Callable[[TaskProgress], None] | None = None,
        timeout: float | None = None,
        mode: Mode | None = None,
        store_output: str | None = None,
        webhook_url: str | None = None,
        idempotency_key: str | None = None,
        async_: bool | None = None,
        upload: UploadOptions | None = None,
        inline_images: bool = False,
    ) -> dict[str, Any]:
        """Speech-to-text. ``audio_url`` may be a link or bytes / a path / a file-like object (uploaded first). Returns
        ``{text, language?, duration?}``."""
        return self._run(
            model,
            input,
            on_progress=on_progress,
            timeout=timeout,
            mode=mode,
            store_output=store_output,
            webhook_url=webhook_url,
            idempotency_key=idempotency_key,
            async_=async_,
            upload=upload,
            inline_images=inline_images,
        )
