# GENERATED by scripts/unasync.py from relaygpu/_async/. Do not edit; edit the async source and rerun.
"""The async client (port of src/client.ts). ``_sync/client.py`` (``Relay``) is generated from this file."""

from __future__ import annotations

from collections.abc import Callable, Mapping
from types import TracebackType
from typing import Any

import httpx

from .._core import _UNSET, Query, RawBody, RetryOptions
from ..types import AsyncAccepted, CostEstimate, HealthResponse, Mode, TaskProgress, UploadOptions, UsageInput
from ._http import HttpClient
from .account import Account
from .audio import Audio
from .estimate import estimate_cost
from .files import Files
from .image import Images
from .keys import Keys
from .models import Models, Pricing, Tiers, health
from .run import run
from .tasks import Tasks
from .video import Videos
from .webhooks import Webhooks
from .workflows import Workflows


class Relay:
    """The Relay client.

    ``api_key`` (``relay_sk_…``) is sent as ``X-API-Key``; ``jwt`` (a dashboard login token) as ``Authorization:
    Bearer``; never both. Catalog reads (``models``, ``pricing``, ``tiers``, ``health``) and task polls need no
    credential. ``timeout`` is seconds per HTTP attempt (default 600). ``retry=False`` disables every retry.
    """

    def __init__(
        self,
        api_key: str | None = None,
        *,
        jwt: str | None = None,
        base_url: str | None = None,
        timeout: float | None = None,
        retry: bool | RetryOptions | None = None,
        default_headers: Mapping[str, str] | None = None,
        http_client: httpx.Client | None = None,
    ) -> None:
        self._http = HttpClient(
            api_key=api_key,
            jwt=jwt,
            base_url=base_url,
            timeout=timeout,
            retry=retry,
            default_headers=default_headers,
            http_client=http_client,
        )
        self.models = Models(self)
        self.pricing = Pricing(self)
        self.tiers = Tiers(self)
        self.tasks = Tasks(self)
        self.image = Images(self)
        self.video = Videos(self)
        self.audio = Audio(self)
        self.files = Files(self)
        self.workflows = Workflows(self)
        self.account = Account(self)
        self.keys = Keys(self)
        self.webhooks = Webhooks(self)

    @property
    def base_url(self) -> str:
        return self._http.base_url

    def __repr__(self) -> str:
        # Never reveal the credential when the client is logged or printed.
        return f"Relay(base_url={self._http.base_url!r})"

    def health(self) -> HealthResponse:
        """``GET /v2/health``."""
        return health(self)

    def run(
        self,
        model: str,
        input: Mapping[str, Any],
        *,
        wait: bool = True,
        on_progress: Callable[[TaskProgress], None] | None = None,
        timeout: float | None = None,
        mode: Mode | None = None,
        store_output: str | None = None,
        webhook_url: str | None = None,
        idempotency_key: str | None = None,
        async_: bool | None = None,
        upload: UploadOptions | None = None,
        inline_images: bool = False,
    ) -> dict[str, Any] | AsyncAccepted:
        """Runs any model: resolves its route through ``models.get``, submits, and (by default) waits for the result.

        A sync route returns its body; an async route (or ``async_=True``) waits and returns the task's ``result``;
        ``wait=False`` returns the ``202`` envelope instead (narrow with ``is_accepted``).
        """
        return run(
            self,
            model,
            input,
            wait=wait,
            on_progress=on_progress,
            timeout=timeout,
            mode=mode,
            store_output=store_output,
            webhook_url=webhook_url,
            idempotency_key=idempotency_key,
            async_=async_,
            upload=upload,
            inline_images=inline_images,
        )

    def estimate_cost(self, model: str, usage: UsageInput) -> CostEstimate:
        """Client-side estimate from ``/v2/pricing`` rows. An estimate, never an invoice."""
        return estimate_cost(self, model, usage)

    def request(
        self,
        method: str,
        path: str,
        *,
        json: Any = _UNSET,
        query: Query | None = None,
        headers: Mapping[str, str] | None = None,
        content: RawBody | None = None,
        content_type: str | None = None,
        timeout: float | None = None,
        idempotency_key: str | None = None,
        no_auth: bool = False,
    ) -> Any:
        """Escape hatch: any route, typed errors and the retry policy included. Returns the parsed body."""
        res = self._http.request(
            method,
            path,
            json=json,
            query=query,
            headers=headers,
            content=content,
            content_type=content_type,
            timeout=timeout,
            idempotency_key=idempotency_key,
            no_auth=no_auth,
        )
        return res.data

    def close(self) -> None:
        """Closes the HTTP connection pool (not a ``http_client`` you passed in)."""
        self._http.close()

    def __enter__(self) -> Relay:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        self.close()
