# GENERATED by scripts/unasync.py from relaygpu/_async/. Do not edit; edit the async source and rerun.
"""``POST|GET|DELETE /v2/files`` and the implicit upload (port of src/files.ts). Hand-written async;
``_sync/files.py`` is generated from it by scripts/unasync.py. The pure rules live in ``relaygpu/inputs.py``."""

from __future__ import annotations

import base64
import os
from collections.abc import Iterator, Mapping
from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal, cast

from .._core import ReplayableBody
from .._util import path_id
from ..inputs import (
    CHUNK_SIZE,
    HEAD,
    INLINE_IMAGE_MAX_BYTES,
    UPLOAD_TYPE_ERROR,
    FileData,
    as_chunk,
    sync_read,
    collect_files,
    contains_file,
    file_name_of,
    is_async_iterator,
    is_bytes_like,
    is_file_data,
    is_stream,
    size_of,
    sniff_media_type,
    substitute,
    unknown_type_error,
)
from ..types import FileListResponse, FileObject, Retention, UploadOptions

if TYPE_CHECKING:
    from .._core import RawBody
    from .client import Relay

__all__ = ["INLINE_IMAGE_MAX_BYTES", "Files"]


def _path(file_id: str) -> str:
    return f"/v2/files/{path_id(file_id)}"


def _refuse_foreign_stream(data: object) -> None:
    """The async client reads every stream. Its generated sync twin reads ``isinstance(data, Iterator)`` here, so an
    async iterator handed to ``Relay`` is refused before anything is sent."""
    if is_async_iterator(data) and not isinstance(data, Iterator):
        raise TypeError("Relay: the sync client cannot read an async iterator; pass an iterator of bytes, or use the async client")


def _chunks(data: Any) -> Iterator[bytes]:
    """Every byte of a path, a file object or an iterator, in chunks; never the whole file in memory."""
    if isinstance(data, os.PathLike):
        with open(data, "rb") as f:
            while chunk := sync_read(f, CHUNK_SIZE):
                yield chunk
    elif callable(getattr(data, "read", None)):
        while chunk := sync_read(data, CHUNK_SIZE):
            yield chunk
    elif isinstance(data, Iterator):
        for c in data:
            yield as_chunk(c)
    else:
        for c in data:
            yield as_chunk(c)


class _PathBody(ReplayableBody):
    """A path's bytes as a request body that re-opens the file on each iteration, so the transport may resend it."""

    def __init__(self, path: os.PathLike[str]) -> None:
        self._path = path

    def __iter__(self) -> Iterator[bytes]:
        return _chunks(self._path)


def _peek(src: Iterator[bytes], n: int) -> tuple[bytes, Iterator[bytes]]:
    """Reads at least ``n`` bytes (or to the end) and returns them plus an iterator that replays everything."""
    chunks: list[bytes] = []
    have = 0
    while have < n:
        try:
            c = src.__next__()
        except StopIteration:
            break
        chunks.append(c)
        have += len(c)

    def replay() -> Iterator[bytes]:
        for c in chunks:
            yield c
        for c in src:
            yield c

    return b"".join(chunks)[:n], replay()


def _media_type_of(data: Any) -> str | None:
    """The type sniffed from the first bytes of bytes or a path (never a stream: it can be read once)."""
    if is_bytes_like(data):
        return sniff_media_type(bytes(data[:HEAD]))
    if isinstance(data, os.PathLike):
        with open(data, "rb") as f:
            return sniff_media_type(f.read(HEAD))
    return None


def _resolve(data: Any, explicit: str | None) -> tuple[RawBody, str | None]:
    """The request body and media type (``explicit`` → sniffed magic bytes) without consuming the data: a path is
    re-opened to stream, a file object or an iterator is peeked and handed back whole."""
    if is_bytes_like(data):
        return bytes(data), explicit or _media_type_of(data)
    if isinstance(data, os.PathLike):
        return _PathBody(data), explicit or _media_type_of(data)
    stream = _chunks(data)
    if explicit:
        return stream, explicit
    head, replay = _peek(stream, HEAD)
    return replay, sniff_media_type(head)


def _inline(data: Any, data_uri: bool, key: str) -> str:
    """The file as raw base64, or as a data URI typed from its first bytes. Reads the data once."""
    if data_uri and is_stream(data):
        raise unknown_type_error(f'field "{key}"')  # a stream is never sniffed: it can be read once
    buf = bytes(data) if is_bytes_like(data) else b"".join([c for c in _chunks(data)])
    b64 = base64.b64encode(buf).decode("ascii")
    if not data_uri:
        return b64
    media_type = sniff_media_type(buf[:HEAD])
    if not media_type:
        raise unknown_type_error(f'field "{key}"')
    return f"data:{media_type};base64,{b64}"


class Files:
    """``POST|GET|DELETE /v2/files``: host an image, video or audio file and get a link any ``*_url`` field takes."""

    def __init__(self, relay: Relay) -> None:
        self._relay = relay

    def upload(
        self,
        data: FileData | str,
        *,
        retention: Retention | None = None,
        filename: str | None = None,
        content_type: str | None = None,
        idempotency_key: str | None = None,
    ) -> FileObject:
        """Uploads the raw bytes and returns the hosted file (``url`` is the link).

        ``data``: bytes, a path (``pathlib.Path`` or ``str``), a binary file object, or an iterator of bytes (the
        async client also takes an async iterator). Paths and file objects are streamed in chunks; a path, a file
        object or an iterator is sent once, never retried. ``content_type`` defaults to the type sniffed from the first bytes;
        ``filename`` to the path's / file object's name; ``retention`` to ``relay1h`` (server-side).
        """
        if isinstance(data, str):
            data = Path(data)
        if not is_file_data(data):
            raise TypeError(UPLOAD_TYPE_ERROR)
        _refuse_foreign_stream(data)
        body, media_type = _resolve(data, content_type)
        if not media_type:
            raise unknown_type_error("the upload")
        # A path's size is known, so it rides as Content-Length (as a Blob's does) instead of a chunked body.
        size = size_of(data) if isinstance(data, os.PathLike) else None
        res = self._relay._http.request(
            "POST",
            "/v2/files",
            content=body,
            content_type=media_type,
            headers={"Content-Length": str(size)} if size is not None else None,
            query={"retention": retention, "filename": filename if filename is not None else file_name_of(data)},
            idempotency_key=idempotency_key,
        )
        return cast(FileObject, res.data)

    def copy(
        self,
        url: str,
        *,
        retention: Retention | None = None,
        filename: str | None = None,
        idempotency_key: str | None = None,
    ) -> FileObject:
        """Has Relay copy a public http(s) object (the JSON form; ``retention`` / ``filename`` ride in the body)."""
        body: dict[str, str] = {"url": url}
        if retention is not None:
            body["retention"] = retention
        if filename is not None:
            body["filename"] = filename
        res = self._relay._http.request("POST", "/v2/files", json=body, idempotency_key=idempotency_key)
        return cast(FileObject, res.data)

    def get(self, file_id: str) -> FileObject:
        """One file. Unknown, foreign or long-expired ids raise ``FileNotFoundError`` (``relaygpu.errors``)."""
        res = self._relay._http.request("GET", _path(file_id))
        return cast(FileObject, res.data)

    def list(
        self,
        *,
        source: Literal["upload", "result"] | None = None,
        status: Literal["ready", "expired"] | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> FileListResponse:
        """One page, newest first: uploads and hosted results. Follow ``next_cursor`` (``None`` on the last page).
        ``limit`` is 1–200, default 50."""
        query = {"source": source, "status": status, "limit": limit, "cursor": cursor}
        res = self._relay._http.request("GET", "/v2/files", query=query)
        return cast(FileListResponse, res.data)

    def list_all(
        self,
        *,
        source: Literal["upload", "result"] | None = None,
        status: Literal["ready", "expired"] | None = None,
        limit: int | None = None,
        cursor: str | None = None,
    ) -> Iterator[FileObject]:
        """Every file across pages, following ``next_cursor``."""
        while True:
            page = self.list(source=source, status=status, limit=limit, cursor=cursor)
            files = page["files"]
            for f in files:
                yield f
            nxt = page.get("next_cursor")
            if not nxt or not files or nxt == cursor:
                return
            cursor = nxt

    def delete(self, file_id: str) -> None:
        """Takes the link down now (idempotent; no refund)."""
        self._relay._http.request("DELETE", _path(file_id))

    def prepare_inputs(
        self,
        input: Mapping[str, Any],
        *,
        upload: UploadOptions | None = None,
        inline_images: bool = False,
        request_schema: Mapping[str, Any] | None = None,
    ) -> dict[str, Any]:
        """The implicit upload: a copy of ``input`` with every file in a ``*_url`` / ``*_urls`` field (nested too)
        uploaded and replaced by its link, or — per the route's request schema — inlined as base64:

        - a ``*_url`` / ``*_urls`` field, or a field whose schema says it takes a URL → uploaded, replaced by its link;
        - with ``inline_images``, an image ≤ 4 MB (bytes or a path) in a field whose schema says it takes base64 →
          inlined (a data URI for URL-shaped fields and fields that name data URIs, raw base64 otherwise);
        - a field that takes base64 only (no URL) → always inlined, whatever the size;
        - anything else → ``TypeError``, before the first upload.

        A ``str`` is never file data here (it is the URL or base64 the caller wrote). One upload per distinct file
        object (identity) per call. A body without files makes no calls.
        """
        if not contains_file(input):
            return dict(input)
        found = collect_files(input, request_schema)  # refuses a misplaced file before the first upload
        for data, _f, _r in found:
            _refuse_foreign_stream(data)
        chosen = (upload or {}).get("retention")
        retention = chosen if chosen is not None else "relay1h"
        done: dict[tuple[int, str], str] = {}  # one upload / encoding per distinct object and form
        keep: list[object] = []  # holds each object so its id() is not reused during the call
        out: list[str] = []
        for data, f, rule in found:
            if not rule.base64:
                inline = False
            elif not rule.url:
                inline = True  # base64-only: inlining is the only way in, whatever the size (a stream is read into memory)
            else:
                size = size_of(data)  # None for a stream: never inlined
                inline = (
                    inline_images
                    and size is not None
                    and size <= INLINE_IMAGE_MAX_BYTES
                    and (_media_type_of(data) or "").startswith("image/")
                )
            key = (id(data), ("uri" if rule.data_uri else "raw") if inline else "upload")
            if key not in done:
                keep.append(data)
                if inline:
                    done[key] = _inline(data, rule.data_uri, f.key)
                else:
                    done[key] = (self.upload(data, retention=retention, filename=file_name_of(data)))["url"]
            out.append(done[key])
        return cast("dict[str, Any]", substitute(input, iter(out)))
