# GENERATED by scripts/unasync.py from relaygpu/_async/. Do not edit; edit the async source and rerun.
"""Image generation and editing (port of src/image.ts). The parsing lives in ``relaygpu/_images.py``."""

from __future__ import annotations

from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

import httpx

from .._core import DEFAULT_TIMEOUT
from .._exceptions import APIConnectionError, APITimeoutError
from .._images import decode_b64, download_error, image_values, parse_image_value
from ..types import KnownImageModel, Mode, TaskProgress, UploadOptions
from .run import run

if TYPE_CHECKING:
    from .client import Relay

__all__ = ["ImageResult", "Images", "RelayImage", "normalise_images", "to_relay_image"]


def _download_client() -> httpx.Client:
    """A plain client for result links: never the Relay client, so never the Relay credential."""
    return httpx.Client(follow_redirects=True, timeout=DEFAULT_TIMEOUT)


@dataclass(frozen=True, repr=False)
class RelayImage:
    """One output image, URL- or base64-backed. URLs expire (1 h by default; ``store_output`` buys 1/7/30 d)."""

    url: str | None = None
    b64: str | None = None
    """Raw base64 (no ``data:`` prefix)."""
    mime_type: str | None = None

    def __repr__(self) -> str:
        if self.url is not None:
            return f"{type(self).__name__}(url={self.url!r})"
        return f"{type(self).__name__}(b64=<{len(self.b64 or '')} chars>, mime_type={self.mime_type!r})"

    def to_bytes(self) -> bytes:
        """Downloads (URL; no Relay credential is sent) or decodes (base64) the bytes."""
        if self.url is None:
            return decode_b64(self.b64 or "")
        with _download_client() as client:
            try:
                res = client.get(self.url)
            except httpx.TimeoutException:
                raise APITimeoutError(f"Image download timed out: {self.url}") from None
            except httpx.TransportError as e:
                raise APIConnectionError(f"Image download failed: {type(e).__name__}: {e}") from None
            if not res.is_success:
                raise download_error(res.status_code)
            return res.content

    def save(self, path: str | Path) -> None:
        """Writes the bytes to a file."""
        data = self.to_bytes()
        Path(path).write_bytes(data)


@dataclass(frozen=True)
class ImageResult:
    """``images``: every output image, normalised. ``raw``: the response body (or the async task's ``result``) exactly
    as the API sent it."""

    images: list[RelayImage] = field(default_factory=list)
    raw: dict[str, Any] = field(default_factory=dict)


def to_relay_image(value: str, mime_hint: str | None = None) -> RelayImage:
    """Builds a ``RelayImage`` from a URL, a data URI or a bare base64 string."""
    url, b64, mime = parse_image_value(value, mime_hint)
    return RelayImage(url=url, b64=b64, mime_type=mime)


def normalise_images(body: Mapping[str, Any], input: Mapping[str, Any] | None = None) -> list[RelayImage]:
    """Normalises every image response shape the live routes use: ``urls[]``, ``images[]`` (base64 or links),
    OpenAI-style ``data[]``, single ``url`` / ``image``."""
    values, hint = image_values(body, input)
    return [to_relay_image(v, hint) for v in values]


class Images:
    """Image generation and editing. Both methods take any image model; the route comes from ``relay.models.get``."""

    def __init__(self, relay: Relay) -> None:
        self._relay = relay

    def generate(
        self,
        model: KnownImageModel | str,
        input: Mapping[str, Any],
        *,
        on_progress: Callable[[TaskProgress], None] | None = None,
        timeout: float | None = None,
        mode: Mode | None = None,
        store_output: str | None = None,
        webhook_url: str | None = None,
        idempotency_key: str | None = None,
        async_: bool | None = None,
        upload: UploadOptions | None = None,
        inline_images: bool = False,
    ) -> ImageResult:
        """Generates images. Returns ``ImageResult(images, raw)`` with every image normalised to a ``RelayImage`` (URL or
        base64). If the route answers async (``async_=True``), waits for the task like ``run()`` does; ``timeout`` is
        that wait's budget (default 20 min) and the per-attempt HTTP timeout of a sync call."""
        raw = run(
            self._relay,
            model,
            input,
            wait=True,
            on_progress=on_progress,
            timeout=timeout,
            mode=mode,
            store_output=store_output,
            webhook_url=webhook_url,
            idempotency_key=idempotency_key,
            async_=async_,
            upload=upload,
            inline_images=inline_images,
        )
        body = cast("dict[str, Any]", raw)  # wait=True: never the 202 envelope
        return ImageResult(images=normalise_images(body, input), raw=body)

    def edit(
        self,
        model: KnownImageModel | str,
        input: Mapping[str, Any],
        *,
        on_progress: Callable[[TaskProgress], None] | None = None,
        timeout: float | None = None,
        mode: Mode | None = None,
        store_output: str | None = None,
        webhook_url: str | None = None,
        idempotency_key: str | None = None,
        async_: bool | None = None,
        upload: UploadOptions | None = None,
        inline_images: bool = False,
    ) -> ImageResult:
        """Image-to-image editing (``image`` / ``images`` / ``*_url`` inputs; file values are uploaded). Same contract
        as ``generate``."""
        return self.generate(
            model,
            input,
            on_progress=on_progress,
            timeout=timeout,
            mode=mode,
            store_output=store_output,
            webhook_url=webhook_url,
            idempotency_key=idempotency_key,
            async_=async_,
            upload=upload,
            inline_images=inline_images,
        )
