# GENERATED by scripts/unasync.py from relaygpu/_async/. Do not edit; edit the async source and rerun.
"""STUB (lead scaffold): the owning package replaces this file."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .client import Relay


class Models:
    def __init__(self, relay: Relay) -> None:
        self._relay = relay


class Pricing:
    def __init__(self, relay: Relay) -> None:
        self._relay = relay


class Tiers:
    def __init__(self, relay: Relay) -> None:
        self._relay = relay


def health(relay: Relay) -> Any:
    raise NotImplementedError
