"""Regenerates relaygpu/_generated/ from Relay's public OpenAPI spec (the port of the TS scripts/gen.mjs).

Source: RELAY_SPEC_URL, else ``${RELAY_BASE_URL}/v2/openapi-public.json``, else prod. ``--spec FILE`` reads a local copy.
Deterministic: the same spec always writes the same bytes (the drift job diffs the output).
"""

from __future__ import annotations

import argparse
import json
import keyword
import os
import re
import sys
import urllib.request
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "relaygpu" / "_generated"
STATUSES = ROOT / "scripts" / "error_statuses.json"

BANNER = "# GENERATED by scripts/gen.py from the public OpenAPI spec. Do not edit; run `python scripts/gen.py`.\n"

# HTTP status → base class (the TS BASES table).
BASES = {
    400: "InvalidRequestError",
    401: "AuthenticationError",
    402: "InsufficientCreditsError",
    403: "PermissionDeniedError",
    404: "NotFoundError",
    409: "ConflictError",
    410: "GoneError",
    422: "ValidationError",
    429: "RateLimitError",
    500: "RelayInternalError",
    502: "ProviderError",
    503: "CapacityError",
    504: "UpstreamTimeoutError",
}

IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def load_spec(path: str | None) -> tuple[dict[str, Any], str]:
    if path:
        return json.loads(Path(path).read_text("utf-8")), path
    base = os.environ.get("RELAY_BASE_URL") or "https://relaygpu.com"
    url = os.environ.get("RELAY_SPEC_URL") or f"{base.rstrip('/')}/v2/openapi-public.json"
    with urllib.request.urlopen(url, timeout=60) as res:
        return json.loads(res.read()), url


def pascal(s: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[^A-Za-z0-9]+", s) if p)


def py_literal(v: Any) -> str:
    if v is None:
        return "None"
    if isinstance(v, bool):
        return "True" if v else "False"
    if isinstance(v, str):
        return json.dumps(v)
    return repr(v)


class TypeGen:
    """Component schemas → TypedDicts (objects) and type aliases (everything else)."""

    def __init__(self, schemas: dict[str, Any]) -> None:
        self.schemas = schemas
        self.blocks: list[str] = []
        self.names: set[str] = set(schemas)
        self.used_any = False

    def ref(self, r: str) -> str:
        return r.rsplit("/", 1)[-1]

    def expr(self, s: Any, hint: str) -> str:
        """A type expression for schema `s`; `hint` names an inline object if one is needed."""
        if s is True or s is None or s == {}:
            self.used_any = True
            return "Any"
        if s is False:
            return "None"
        if "$ref" in s:
            return self.ref(s["$ref"])
        if "const" in s:
            return f"Literal[{py_literal(s['const'])}]"
        if "enum" in s:
            vals = [v for v in s["enum"] if v is not None]
            out = f"Literal[{', '.join(py_literal(v) for v in vals)}]" if vals else "None"
            return out + " | None" if None in s["enum"] and vals else out
        for key in ("anyOf", "oneOf", "allOf"):
            if key in s:
                if key == "allOf" and len(s[key]) == 1:
                    return self.expr(s[key][0], hint)
                if key == "allOf":
                    self.used_any = True
                    return "dict[str, Any]"
                parts = [self.expr(m, f"{hint}{i}" if i else hint) for i, m in enumerate(s[key])]
                return self.union(parts)
        t = s.get("type")
        if isinstance(t, list):
            return self.union([self.expr({**s, "type": x}, hint) for x in t])
        if t == "string":
            return "str"
        if t == "integer":
            return "int"
        if t == "number":
            return "float"
        if t == "boolean":
            return "bool"
        if t == "null":
            return "None"
        if t == "array":
            return f"list[{self.expr(s.get('items', {}), hint + 'Item')}]"
        if t == "object" or "properties" in s or "additionalProperties" in s:
            if s.get("properties"):
                name = self.unique(hint)
                self.typeddict(name, s)
                return name
            ap = s.get("additionalProperties")
            self.used_any = True
            if isinstance(ap, dict) and ap:
                return f"dict[str, {self.expr(ap, hint + 'Value')}]"
            return "dict[str, Any]"
        self.used_any = True
        return "Any"

    def union(self, parts: list[str]) -> str:
        seen: list[str] = []
        for p in parts:
            for q in p.split(" | "):
                if q not in seen:
                    seen.append(q)
        if "Any" in seen:
            return "Any"
        if "None" in seen:  # None last
            seen = [q for q in seen if q != "None"] + ["None"]
        return " | ".join(seen)

    def unique(self, hint: str) -> str:
        name, i = hint, 2
        while name in self.names:
            name, i = f"{hint}{i}", i + 1
        self.names.add(name)
        return name

    def typeddict(self, name: str, s: dict[str, Any]) -> None:
        props: dict[str, Any] = s.get("properties") or {}
        required = set(s.get("required") or [])
        fields: list[tuple[str, str]] = []
        for prop in props:  # spec order: stable and close to the docs
            t = self.expr(props[prop], name + pascal(prop))
            fields.append((prop, f"Required[{t}]" if prop in required else t))
        doc = (s.get("description") or s.get("title") or "").strip().splitlines()
        functional = any(not IDENT.match(p) or keyword.iskeyword(p) for p, _ in fields)
        lines: list[str] = []
        if functional:
            # A key that is not an identifier (e.g. `async`): the functional form, types as strings (never evaluated).
            lines.append(f"{name} = TypedDict(")
            lines.append(f"    {json.dumps(name)},")
            lines.append("    {")
            for p, t in fields:
                lines.append(f"        {json.dumps(p)}: {t!r},")
            lines.append("    },")
            lines.append("    total=False,")
            lines.append(")")
            if doc and doc[0]:
                lines.insert(0, f"# {doc[0]}")
        else:
            lines.append(f"class {name}(TypedDict, total=False):")
            if doc and doc[0]:
                lines.append(f'    """{doc[0].replace(chr(92), "/").replace(chr(34) * 3, "")}"""')
                if fields:
                    lines.append("")
            for p, t in fields:
                lines.append(f"    {p}: {t}")
            if not fields and not (doc and doc[0]):
                lines.append("    pass")
        self.blocks.append("\n".join(lines))

    def component(self, name: str, s: dict[str, Any]) -> None:
        if isinstance(s, dict) and s.get("properties") and not any(k in s for k in ("anyOf", "oneOf", "allOf")):
            self.typeddict(name, s)
        else:
            self.blocks.append(f'{name}: TypeAlias = "{self.expr(s, name + "Value")}"')

    def render(self) -> str:
        for name in sorted(self.schemas):
            self.component(name, self.schemas[name])
        head = [
            BANNER,
            '"""Request and response shapes from the public spec: TypedDicts (`total=False`, `Required[...]` where the spec',
            'requires a field) and Literal aliases. Annotations are strings at runtime (never evaluated)."""',
            "",
            "from __future__ import annotations",
            "",
            "from typing import TYPE_CHECKING, Any, Literal, TypedDict",
            "",
            "if TYPE_CHECKING:",
            "    from typing_extensions import Required, TypeAlias",
            "else:",
            "    Required = TypeAlias = Any",
            "",
            "",
        ]
        body = "\n\n\n".join(self.blocks)
        names = sorted(n for n in self.names)
        tail = ["", "", "__all__ = ["] + [f"    {json.dumps(n)}," for n in names] + ["]", ""]
        return "\n".join(head) + body + "\n".join(tail)


def gen_models(spec: dict[str, Any]) -> tuple[str, int]:
    """Live model name → operationId per tag (deprecated ops excluded), plus a Literal per family."""
    by_tag: dict[str, dict[str, str]] = {}
    op_bodies: dict[str, str] = {}
    for item in spec["paths"].values():
        for op in item.values():
            if not isinstance(op, dict) or not op.get("operationId"):
                continue
            rb = (((op.get("requestBody") or {}).get("content") or {}).get("application/json") or {}).get("schema") or {}
            if "$ref" in rb:
                op_bodies[op["operationId"]] = rb["$ref"].rsplit("/", 1)[-1]
            if op.get("deprecated") or not isinstance(op.get("x-relay-models"), list):
                continue
            tag = (op.get("tags") or ["Other"])[0]
            for name in op["x-relay-models"]:
                by_tag.setdefault(tag, {})[name] = op["operationId"]
    lines = [BANNER, '"""Known model names (types only: the runtime always resolves through `GET /v2/models/{model}`)."""', ""]
    lines += ["from __future__ import annotations", "", "from typing import Literal", ""]
    lines.append("# Live model names per tag → the operation that serves them (from `x-relay-models`).")
    lines.append("MODEL_OPERATIONS: dict[str, dict[str, str]] = {")
    for tag in sorted(by_tag):
        lines.append(f"    {json.dumps(tag)}: {{")
        for name in sorted(by_tag[tag]):
            lines.append(f"        {json.dumps(name)}: {json.dumps(by_tag[tag][name])},")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("# operationId → the component schema of its JSON request body.")
    lines.append("OPERATION_REQUEST_SCHEMAS: dict[str, str] = {")
    for op_id in sorted(op_bodies):
        lines.append(f"    {json.dumps(op_id)}: {json.dumps(op_bodies[op_id])},")
    lines.append("}")
    lines.append("")

    def literal(alias: str, names: list[str], doc: str) -> None:
        lines.append("")
        lines.append(f"# {doc}")
        if not names:
            lines.append(f"{alias} = str")
            return
        lines.append(f"{alias} = Literal[")
        for n in names:
            lines.append(f"    {json.dumps(n)},")
        lines.append("]")

    audio = by_tag.get("Audio", {})
    literal("KnownImageModel", sorted(by_tag.get("Image", {})), "Image models this release knows (any other name works too).")
    literal("KnownVideoModel", sorted(by_tag.get("Video", {})), "Video models this release knows.")
    literal(
        "KnownSpeechModel", sorted(n for n, o in audio.items() if o != "audio_asr_whisper"), "Text-to-speech models this release knows."
    )
    literal(
        "KnownTranscribeModel", sorted(n for n, o in audio.items() if o == "audio_asr_whisper"), "Speech-to-text models this release knows."
    )
    lines.append("")
    return "\n".join(lines), sum(len(v) for v in by_tag.values())


def class_name(code: str) -> str:
    p = "".join(w.capitalize() for w in code.lower().split("_"))
    return p if code.endswith("_ERROR") else p + "Error"


def gen_errors(spec: dict[str, Any]) -> tuple[str, list[str]]:
    codes: list[str] = spec["components"]["schemas"]["RelayError"]["properties"]["code"]["x-relay-error-codes"]
    statuses: dict[str, int] = json.loads(STATUSES.read_text("utf-8"))
    unmapped = [c for c in codes if c not in statuses]
    imports = [*sorted(set(BASES.values())), "RelayAPIError"]
    lines = [BANNER, '"""Error-code subclasses: codes from `x-relay-error-codes`, HTTP status from scripts/error_statuses.json."""', ""]
    lines += ["from __future__ import annotations", "", "from .._exceptions import (", *[f"    {n}," for n in imports], ")", "", ""]
    table: list[str] = []
    exported: list[str] = []
    for code in codes:
        status = statuses.get(code)
        base = BASES.get(status, "RelayAPIError") if status else "RelayAPIError"
        name = class_name(code)
        if name == base:  # the code IS the base (e.g. VALIDATION_ERROR)
            table.append(f"    {json.dumps(code)}: {base},")
            continue
        lines.append(f"class {name}({base}):")
        lines.append(f'    """`{code}`{f" (HTTP {status})" if status else ""}."""')
        lines.append("")
        lines.append("")
        table.append(f"    {json.dumps(code)}: {name},")
        exported.append(name)
    lines.append("# Every catalog code (`x-relay-error-codes`) → its class.")
    lines.append("ERROR_CODE_CLASSES: dict[str, type[RelayAPIError]] = {")
    lines += table
    lines.append("}")
    lines.append("")
    lines.append("__all__ = [")
    lines += [f"    {json.dumps(n)}," for n in sorted([*exported, "ERROR_CODE_CLASSES"])]
    lines.append("]")
    lines.append("")
    return "\n".join(lines), unmapped


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--spec", help="read the spec from a local file instead of the network")
    args = ap.parse_args()
    spec, src = load_spec(args.spec)
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "types.py").write_text(TypeGen(spec["components"]["schemas"]).render(), "utf-8")
    models, n_models = gen_models(spec)
    (OUT / "models_map.py").write_text(models, "utf-8")
    errors, unmapped = gen_errors(spec)
    (OUT / "error_codes.py").write_text(errors, "utf-8")
    init = OUT / "__init__.py"
    init.write_text(BANNER, "utf-8")
    if unmapped:
        print(
            f"gen: no HTTP status in scripts/error_statuses.json for {', '.join(unmapped)} — they degrade to their response status class",
            file=sys.stderr,
        )
    print(
        f"gen: {src} → relaygpu/_generated/ ({len(spec['paths'])} paths, {len(spec['components']['schemas'])} schemas, {n_models} models)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
