"""Generates relaygpu/_sync/ from the hand-written relaygpu/_async/ (the `unasync` pattern, plan D3).

Token-level: drops `async`/`await`, renames the async names below and every `Async<Name>` class the async sources
define to `<Name>`. In strings and comments only those class names and `await ` are rewritten (so the sync docs read right).
`--check` exits 1 when the committed _sync/ differs from what this script would write (CI and a unit test run it).
"""

from __future__ import annotations

import io
import re
import sys
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "relaygpu" / "_async"
DST = ROOT / "relaygpu" / "_sync"

BANNER = "# GENERATED by scripts/unasync.py from relaygpu/_async/. Do not edit; edit the async source and rerun.\n"

NAMES = {
    "AsyncClient": "Client",
    "AsyncIterator": "Iterator",
    "aclose": "close",
    "aread": "read",
    "__aenter__": "__enter__",
    "__aexit__": "__exit__",
    "__aiter__": "__iter__",
    "__anext__": "__next__",
    "StopAsyncIteration": "StopIteration",
    "async_sleep": "sync_sleep",
    "async_write_bytes": "sync_write_bytes",
    "async_read": "sync_read",
}
CLASS_DEF = re.compile(r"^\s*class (Async[A-Z]\w*)\b", re.M)
# Only the classes the async sources define are renamed (AsyncAccepted, a shared type, keeps its name).
ASYNC_CLASSES = {m: m[len("Async") :] for p in sorted(SRC.glob("*.py")) for m in CLASS_DEF.findall(p.read_text("utf-8"))}
TEXT_RENAMES = [
    *((re.compile(rf"\b{a}\b"), s) for a, s in ASYNC_CLASSES.items()),
    (re.compile(r"\bawait "), ""),
]


# 3.12+ tokenizes f-strings into parts; 3.10/3.11 see one STRING token. Both produce the same output.
TEXT_TOKENS = {tokenize.STRING, tokenize.COMMENT, getattr(tokenize, "FSTRING_MIDDLE", tokenize.STRING)}


def rename(name: str) -> str:
    """The sync twin of an async name (``aclose`` → ``close``, ``AsyncFiles`` → ``Files``); any other name unchanged."""
    return NAMES.get(name) or ASYNC_CLASSES.get(name) or name


def transform(source: str) -> str:
    """Line-based rewrite driven by the tokenizer: every NAME token is renamed in place, `async `/`await ` removed."""
    tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))
    src_lines = source.splitlines(keepends=True)
    # Edits per line, applied right to left so columns stay valid.
    edits: dict[int, list[tuple[int, int, str]]] = {}
    for tok in tokens:
        (r0, c0), (r1, c1) = tok.start, tok.end
        if tok.type == tokenize.NAME and tok.string in ("async", "await"):
            line = src_lines[r0 - 1]
            end = c1
            while end < len(line) and line[end] == " ":
                end += 1
            edits.setdefault(r0, []).append((c0, end, ""))
        elif tok.type == tokenize.NAME:
            new = rename(tok.string)
            if new != tok.string:
                edits.setdefault(r0, []).append((c0, c1, new))
        elif tok.type in TEXT_TOKENS:
            for row in range(r0, r1 + 1):
                line = src_lines[row - 1]
                a = c0 if row == r0 else 0
                b = c1 if row == r1 else len(line)
                seg = line[a:b]
                new_seg = seg
                for rx, rep in TEXT_RENAMES:
                    new_seg = rx.sub(rep, new_seg)
                if new_seg != seg:
                    edits.setdefault(row, []).append((a, b, new_seg))
    for row, row_edits in edits.items():
        line = src_lines[row - 1]
        for a, b, rep in sorted(row_edits, reverse=True):
            line = line[:a] + rep + line[b:]
        src_lines[row - 1] = line
    return "".join(src_lines)


def main() -> int:
    check = "--check" in sys.argv[1:]
    DST.mkdir(parents=True, exist_ok=True)
    expected = {p.name: BANNER + transform(p.read_text("utf-8")) for p in sorted(SRC.glob("*.py"))}
    stale = [p.name for p in DST.glob("*.py") if p.name not in expected]
    drift = [n for n, text in expected.items() if not (DST / n).exists() or (DST / n).read_text("utf-8") != text]
    if check:
        if drift or stale:
            print(
                f"unasync: relaygpu/_sync/ is stale: {', '.join(sorted(drift + stale))}; run `python scripts/unasync.py`", file=sys.stderr
            )
            return 1
        print(f"unasync: relaygpu/_sync/ is current ({len(expected)} files)")
        return 0
    for name in stale:
        (DST / name).unlink()
    for name, text in expected.items():
        (DST / name).write_text(text, "utf-8")
    print(f"unasync: relaygpu/_async/ → relaygpu/_sync/ ({len(expected)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
